{{ config(materialized='table',unique_key="GOAL_ID||'-'||ACTIVITY_ID||'-'||LEARNING_ACTIVITY_ID" ,transient=false) }}


select
to_date(NULLIF(LAST_MODIFIED_DATE,''),'MM/DD/YYYY') as LAST_MODIFICATION_DATE,
DEVELOPMENT_GOAL_ID ,
GOAL_OWNER_USERNAME ,
CATEGORY ,
TYPE ,
VISIBILITY_OF_YOUR_GOAL ,
GOAL_NAME ,
to_date(NULLIF(DUE_DATE,''),'MM/DD/YYYY') as DUE_DATE,
STATUS as GOAL_STATUS ,
ACTIVE_DELETED AS GOAL_ACTIVE_DELETED ,
to_date(NULLIF(CREATED_DATE,''),'MM/DD/YYYY')  as CREATED_DATE,
LEARNING_ACTIVITY_ID,
LEARNING_STATUS,
to_date(NULLIF(COMPLETED_DATE,''),'MM/DD/YYYY') as GLA_COMPLETED_DATE,
ACTIVE AS IS_GLA_ACTIVE,
NAME AS LEARNING_ACTIVITY_NAME,
NULL ::string AS ACTIVITY_ID,
NULL ::string AS ACTIVITY_NAME,
NULL ::string AS ACTIVITY_STATUS,
NULL ::string AS  ACTIVITY_LAST_MODIFICATION_DATE,
NULL ::string AS  ACTIVITY_CREATION_DATE
FROM {{ source('landing_tables_PMG', 'DEV_GOAL_REPORT') }}
where DEVELOPMENT_GOAL_ID  is not null 
