select
	FYEF_YE_FORM_KEY_DDEP as S_KEY,
	FYEF_FORMDATA_ID_FYEF as FORMDATA_ID,
	FYEF_EMPLOYEE_PROFILE_KEY_DDEP as EMP_ID ,
	FYEF_EMPLOYEE_MANAGER_KEY_DDEP as MANAGER_ID ,
	FYEF_FORM_NAME_FYEF as FORM_TITLE,
        FYEF_FORM_TEMPLATE_ID_FYEF as FORM_TEMPLATE_ID,
	FYEF_PE_FORMCONTENT_ID_FYEF AS PE_FORMCONTENT_ID ,

	FYEF_PE_PG_RATING_KEY_DYER AS PE_PG_RATING,
    Case When PE_PG_RATING.DYER_CODE_DYER in (1.0,2.0,3.0,4.0,5.0)
         Then PE_PG_RATING.DYER_CODE_DYER  || ' - ' || PE_PG_RATING.DYER_LABEL_DYER
         Else PE_PG_RATING.DYER_LABEL_DYER End As PE_PG_RATING_LABEL,

	FYEF_PE_BG_RATING_KEY_DYER AS PE_BG_RATING,
    Case When PE_BG_RATING.DYER_CODE_DYER in (1.0,2.0,3.0,4.0,5.0)
         Then PE_BG_RATING.DYER_CODE_DYER  || ' - ' || PE_BG_RATING.DYER_LABEL_DYER
         Else PE_BG_RATING.DYER_LABEL_DYER End As PE_BG_RATING_LABEL,

	FYEF_PE_OR_RATING_KEY_DYER AS PE_OR_RATING,
    Case When PE_OR_RATING.DYER_CODE_DYER in (1.0,2.0,3.0,4.0,5.0)
         Then PE_OR_RATING.DYER_CODE_DYER  || ' - ' || PE_OR_RATING.DYER_LABEL_DYER
         Else PE_OR_RATING.DYER_LABEL_DYER End As PE_OR_RATING_LABEL,

	FYEF_PE_MANAGER_COMMENTS_FYEF AS PE_MANAGER_COMMENTS,
	FYEF_PE_LMDATE_FYEF AS PE_LMDATE,
	FYEF_YE_FORMCONTENT_ID_FYEF AS YE_FORMCONTENT_ID,

	FYEF_YE_PG_RATING_KEY_DYER AS YE_PG_RATING,
    Case When YE_PG_RATING.DYER_CODE_DYER in (1.0,2.0,3.0,4.0,5.0)
         Then YE_PG_RATING.DYER_CODE_DYER  || ' - ' || YE_PG_RATING.DYER_LABEL_DYER
         Else YE_PG_RATING.DYER_LABEL_DYER End As YE_PG_RATING_LABEL,

	FYEF_YE_BG_RATING_KEY_DYER AS YE_BG_RATING,
    Case When YE_BG_RATING.DYER_CODE_DYER in (1.0,2.0,3.0,4.0,5.0)
         Then YE_BG_RATING.DYER_CODE_DYER  || ' - ' || YE_BG_RATING.DYER_LABEL_DYER
         Else YE_BG_RATING.DYER_LABEL_DYER End As YE_BG_RATING_LABEL,

	FYEF_YE_OR_RATING_KEY_DYER AS YE_OR_RATING,
    Case When YE_OR_RATING.DYER_CODE_DYER in (1.0,2.0,3.0,4.0,5.0)
         Then YE_OR_RATING.DYER_CODE_DYER  || ' - ' || YE_OR_RATING.DYER_LABEL_DYER
         Else YE_OR_RATING.DYER_LABEL_DYER End As YE_OR_RATING_LABEL,

	FYEF_YE_CONVERSATION_DATE_FYEF AS YE_CONVERSATION_DATE,
	FYEF_YE_MANAGER_COMMENTS_FYEF AS YE_MANAGER_COMMENTS,
	FYEF_YE_EMPLOYEE_COMMENTS_FYEF AS YE_EMPLOYEE_COMMENTS,
	FYEF_YE_LMDATE_FYEF  AS YE_LMDATE,
	FYEF_SGN_FORMCONTENT_ID_FYEF AS SGN_FORMCONTENT_ID ,
	FYEF_SGN_EMP_SIGN_FYEF AS SGN_EMP_SIGN,
	FYEF_SGN_MANAGER_SIGN_FYEF AS SGN_MANAGER_SIGN,
	FYEF_SGN_LMDATE_FYEF AS SGN_LMDATE,
	FYEF_SGN_EMPLOYEE_COMMENTS_FYEF AS SGN_EMPLOYEE_COMMENTS,
	FYEF_SGN_MANAGER_COMMENTS_FYEF AS SGN_MANAGER_COMMENTS,
	FYEF_IS_FORM_LAUNCHED_FYEF AS IS_FORM_LAUNCHED,
	FYEF_YE_EMPLOYEE_LMDATE_FYEF AS YE_EMPLOYEE_LMDATE,
	FYEF_YE_MANAGER_LMDATE_FYEF AS YE_MANAGER_LMDATE,
	FYEF_SGN_EMPLOYEE_LMDATE_FYEF AS SGN_EMPLOYEE_LMDATE,
	FYEF_SGN_MANAGER_LMDATE_FYEF AS SGN_MANAGER_LMDATE,
	FYEF_SGN_EMPLOYEE_DATE_FYEF AS SGN_EMPLOYEE_DATE,
	FYEF_SGN_MANAGER_DATE_FYEF AS SGN_MANAGER_DATE,
	FYEF_FORM_STATUS_FYEF AS FORM_STATUS,
    FYEF_FORMDATA_STATUS_FYEF AS FORMDATA_STATUS
  FROM
    {{ ref('fact_ye_form') }}
  Left Outer Join
    {{ ref('dim_ye_form_ratings') }} PE_PG_RATING
    On IFNULL(PE_PG_RATING.DYER_SK_DYER, 6) = IFNULL(FYEF_PE_PG_RATING_KEY_DYER, 6)
  Left Outer Join
    {{ ref('dim_ye_form_ratings') }} PE_BG_RATING
    On IFNULL(PE_BG_RATING.DYER_SK_DYER, 6) = IFNULL(FYEF_PE_BG_RATING_KEY_DYER, 6)
  Left Outer Join
    {{ ref('dim_ye_form_ratings') }} PE_OR_RATING
    On IFNULL(PE_OR_RATING.DYER_SK_DYER, 6) = IFNULL(FYEF_PE_OR_RATING_KEY_DYER, 6)
  Left Outer Join
    {{ ref('dim_ye_form_ratings') }} YE_PG_RATING
    On IFNULL(YE_PG_RATING.DYER_SK_DYER, 6) = IFNULL(FYEF_YE_PG_RATING_KEY_DYER, 6)
  Left Outer Join
    {{ ref('dim_ye_form_ratings') }} YE_BG_RATING
    On IFNULL(YE_BG_RATING.DYER_SK_DYER, 6) = IFNULL(FYEF_YE_BG_RATING_KEY_DYER, 6)
  Left Outer Join
    {{ ref('dim_ye_form_ratings') }} YE_OR_RATING
    On IFNULL(YE_OR_RATING.DYER_SK_DYER, 6) = IFNULL(FYEF_YE_OR_RATING_KEY_DYER, 6)