{{ config(materialized="table", unique_key="EMPLOYEE_ID", transient=true) }}

{% set results =cmp_tables_cnt_chk('YE_COMPENSATION_YE2024') %}
select
    "User ID" as user_id,
    "Employee ID" as employee_id,
    "Legal First Name" as legal_first_name,
    "Legal Last Name" as legal_last_name,
    "Position Title" as position_title,
    "Form Title" as form_title,
    "Current Owner First Name" as current_owner_first_name,
    "Current Owner Last Name" as current_owner_last_name,
    "Manager User Sys ID" as manager_user_sys_id,
    "Manager First Name" as manager_first_name,
    "Manager Last Name" as manager_last_name,
    "HR Manager User Sys ID" as hr_manager_user_sys_id,
    "HR Manager Legal First Name" as hr_manager_legal_first_name,
    "HR Manager Legal Last Name" as hr_manager_legal_last_name,
    "Employee Group" as employee_group,
    "Employee Subgroup" as employee_sub_group,
    "Hire Date" as hire_date,
    "Job Code" as job_code,
    "Professional Field" as professional_field,
    "Specialization" as specialization,
    "Organizational Area" as organizational_area,
    "Functional Area" as functional_area,
    "Global Grade" as global_pay_grade,
    "HR Division" as hr_division,
    "Area" as area,
    "Country" as country,
    "Company" as company,
    "Business Unit" as business_unit,
    "Type Of Business Unit" as type_of_business_unit,
    "Currency Code" as currency_code,
    "Fixed Pay"::number(38,2) as fixed_pay,
    "Total Cash Target (TCT)"::number(38,2) as total_cash_target,
    "Position in Range" as position_in_range_1,
    "Compa-Ratio"::number(38,2) as compa_ratio_1,
    "Gender" as gender,
    "All Player Status" as all_player_status,
    "Rating (Label)" as rating_label,
    "Periodic Base Salary"::number(38,2) as periodic_base_salary,
    "Annualized Salary"::number(38,2) as annualized_salary,
    "Annualized Salary Increase Merit Guideline Low"::number(38,2)
    as annualized_salary_increase_merit_guideline_low,
    "Annualized Salary Increase Merit Guideline Maximum"::number(38,2)
    as annualized_salary_increase_merit_guideline_maximum,
    "Annualized Salary Increase Merit Guideline High"::number(38,2)
    as annualized_salary_increase_merit_guideline_high,
    "Salary Increase Budget (Amount)"::number(38,2) as salary_increase_budget_amount,
    "Promotion Approved" as promotion_approved,
    "Annualized Salary Increase Merit"::number(38,2) as annualized_salary_increase_merit,
    "Total Proposed Spend"::number(38,2) as total_proposed_spend,
    "Base Salary Increase %"::number(38,2) as base_salary_increase_percent,
    "New Annualized Salary"::number(38,2) as new_annualized_salary,
    "New Fixed Pay"::number(38,2) as new_fixed_pay,
    "New Total Cash Target"::number(38,2) as new_total_cash_target,
    "New Position in Range" as new_position_in_range_1,
    "New Compa-Ratio" as new_compa_ratio_1,
    "One-Time Bonus"::number(38,2) as one_time_bonus,
    "Form Template ID" as form_template_id,
    "Form Template Name" as form_template_name,
    "Comp Plan Owner" as comp_plan_owner,
    "Comp Plan Eligibility" as comp_plan_eligibility
from {{ source("landing_tables_CMP", "YE_COMPENSATION_YE2024") }}
