# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'HRDP_SDDS'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'default'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

vars:
 DBT_STAGING_DB: 'HRDP_STG_QA_DB'
 DBT_LANDING_DB: 'HRDP_LND_QA_DB'
# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
  HRDP_SDDS:
    # Applies to all files under models/example/ 
    private:
      +on_schema_change: 'sync_all_columns'
      +database: HRDP_SDDS_{{ env_var('DBT_REGION') }}_DB
      C1_H01_ORGANIZATION_STRUCTURE:
        +schema: BTDP_DS_C1_H01_ORGANIZATION_STRUCTURE_EU_{{ env_var('DBT_REGION') }}_PRIVATE
      C1_H02_JOB_ARCHITECTURE:
        +schema: BTDP_DS_C1_H02_JOB_ARCHITECTURE_EU_{{ env_var('DBT_REGION') }}_PRIVATE
      C1_H03_REWARDS_AND_PAY_STRUCTURE:
        +schema: BTDP_DS_C1_H03_REWARDS_AND_PAY_STRUCTURE_EU_{{ env_var('DBT_REGION') }}_PRIVATE
      C1_H04_PERSON:
        +schema: BTDP_DS_C1_H04_PERSON_EU_{{ env_var('DBT_REGION') }}_PRIVATE
      C1_H05_EMPLOYMENT_INFORMATION:
        +schema: BTDP_DS_C1_H05_EMPLOYMENT_INFORMATION_EU_{{ env_var('DBT_REGION') }}_PRIVATE
      C1_H06_EMPLOYEE_SUBGROUP:
        +schema: BTDP_DS_C1_H06_EMPLOYEE_SUBGROUP_EU_{{ env_var('DBT_REGION') }}_PRIVATE
      C1_H07_EVENT_REASON:
        +schema: BTDP_DS_C1_H07_EVENT_REASON_EU_{{ env_var('DBT_REGION') }}_PRIVATE
      C1_H08_LEARNING:
        +schema: BTDP_DS_C1_H08_LEARNING_EU_{{ env_var('DBT_REGION') }}_PRIVATE
      C1_H09_LOREAL:
        +schema: BTDP_DS_C1_H09_LOREAL_CV_EU_{{ env_var('DBT_REGION') }}_PRIVATE
      C1_H10_DOCUMENT_MANAGEMENT:
        +schema: BTDP_DS_C1_H10_DOCUMENT_MANAGEMENT_EU_{{ env_var('DBT_REGION') }}_PRIVATE
      C1_H11_LEARNING_KPISS:
        +schema: BTDP_DS_C1_H11_LEARNING_KPISS_EU_{{ env_var('DBT_REGION') }}_PRIVATE
      C1_H12_TIME_MANAGEMENT:
        +schema: BTDP_DS_C1_H12_TIME_MANAGEMENT_EU_{{ env_var('DBT_REGION') }}_PRIVATE
      C1_H13_OTHER_REFERENTIALS:
        +schema: BTDP_DS_C1_H13_OTHER_REFERENTIALS_EU_{{ env_var('DBT_REGION') }}_PRIVATE
      C1_H14_KPI_MEASURES:
        +schema: BTDP_DS_C1_H14_KPI_MEASURES_EU_{{ env_var('DBT_REGION') }}_PRIVATE
      C1_H15_REWARDS_INFORMATION:
        +schema: BTDP_DS_C1_H15_REWARDS_INFORMATION_EU_{{ env_var('DBT_REGION') }}_PRIVATE
      C1_H16_CSRD:
        +schema: BTDP_DS_C1_H16_CSRD_EU_{{ env_var('DBT_REGION') }}_PRIVATE
      C1_H17_GROWTH_PORTFOLIO:
        +schema: BTDP_DS_C1_H17_GROWTH_PORTFOLIO_EU_{{ env_var('DBT_REGION') }}_PRIVATE
      C1_H18_ONBOARDING:
        +schema: BTDP_DS_C1_H18_ONBOARDING_EU_{{ env_var('DBT_REGION') }}_PRIVATE
      C1_H19_HR_CONTROLING:
        +schema: BTDP_DS_C1_H19_HR_CONTROLING_EU_{{ env_var('DBT_REGION') }}_PRIVATE
      C1_H20_ADOPTION:
        +schema: BTDP_DS_C1_H20_ADOPTION_EU_{{ env_var('DBT_REGION') }}_PRIVATE
      C1_H21_GENDER_DIVERSITY:
        +schema: BTDP_DS_C1_H21_GENDER_DIVERSITY_EU_{{ env_var('DBT_REGION') }}_PRIVATE
      C1_H22_FINANCE_ORGANIZATION:
        +schema: BTDP_DS_C1_H22_FINANCE_ORGANIZATION_EU_{{ env_var('DBT_REGION') }}_PRIVATE
      C2_H01_ORGANIZATION_STRUCTURE:
        +schema: BTDP_DS_C2_H01_ORGANIZATION_STRUCTURE_EU_{{ env_var('DBT_REGION') }}_PRIVATE
      C2_H02_JOB_ARCHITECTURE:
        +schema: BTDP_DS_C2_H02_JOB_ARCHITECTURE_EU_{{ env_var('DBT_REGION') }}_PRIVATE
      C2_H03_REWARDS_AND_PAY_STRUCTURE:
        +schema: BTDP_DS_C2_H03_REWARDS_AND_PAY_STRUCTURE_EU_{{ env_var('DBT_REGION') }}_PRIVATE
      C2_H04_PERSON:
        +schema: BTDP_DS_C2_H04_PERSON_EU_{{ env_var('DBT_REGION') }}_PRIVATE
      C2_H05_EMPLOYMENT_INFORMATION:
        +schema: BTDP_DS_C2_H05_EMPLOYMENT_INFORMATION_EU_{{ env_var('DBT_REGION') }}_PRIVATE
      C2_H06_EMPLOYEE_SUBGROUP:
        +schema: BTDP_DS_C2_H06_EMPLOYEE_SUBGROUP_EU_{{ env_var('DBT_REGION') }}_PRIVATE
      C2_H07_EVENT_REASON:
        +schema: BTDP_DS_C2_H07_EVENT_REASON_EU_{{ env_var('DBT_REGION') }}_PRIVATE
      C2_H08_LEARNING:
        +schema: BTDP_DS_C2_H08_LEARNING_EU_{{ env_var('DBT_REGION') }}_PRIVATE
      C2_H09_LOREAL:
        +schema: BTDP_DS_C2_H09_LOREAL_CV_EU_{{ env_var('DBT_REGION') }}_PRIVATE
      C2_H10_DOCUMENT_MANAGEMENT:
        +schema: BTDP_DS_C2_H10_DOCUMENT_MANAGEMENT_EU_{{ env_var('DBT_REGION') }}_PRIVATE
      C2_H11_LEARNING_KPISS:
        +schema: BTDP_DS_C2_H11_LEARNING_KPISS_EU_{{ env_var('DBT_REGION') }}_PRIVATE
      C2_H12_TIME_MANAGEMENT:
        +schema: BTDP_DS_C2_H12_TIME_MANAGEMENT_EU_{{ env_var('DBT_REGION') }}_PRIVATE
      C2_H13_OTHER_REFERENTIALS:
        +schema: BTDP_DS_C2_H13_OTHER_REFERENTIALS_EU_{{ env_var('DBT_REGION') }}_PRIVATE
      C2_H14_KPI_MEASURES:
        +schema: BTDP_DS_C2_H14_KPI_MEASURES_EU_{{ env_var('DBT_REGION') }}_PRIVATE
      C2_H15_REWARDS_INFORMATION:
        +schema: BTDP_DS_C2_H15_REWARDS_INFORMATION_EU_{{ env_var('DBT_REGION') }}_PRIVATE
      C2_H16_CSRD:
        +schema: BTDP_DS_C2_H16_CSRD_EU_{{ env_var('DBT_REGION') }}_PRIVATE
      C2_H17_GROWTH_PORTFOLIO:
        +schema: BTDP_DS_C2_H17_GROWTH_PORTFOLIO_EU_{{ env_var('DBT_REGION') }}_PRIVATE
      C2_H18_ONBOARDING:
        +schema: BTDP_DS_C2_H18_ONBOARDING_EU_{{ env_var('DBT_REGION') }}_PRIVATE
      C2_H19_HR_CONTROLING:
        +schema: BTDP_DS_C2_H19_HR_CONTROLING_EU_{{ env_var('DBT_REGION') }}_PRIVATE
      C2_H20_ADOPTION:
        +schema: BTDP_DS_C2_H20_ADOPTION_EU_{{ env_var('DBT_REGION') }}_PRIVATE
      C2_H21_GENDER_DIVERSITY:
        +schema: BTDP_DS_C2_H21_GENDER_DIVERSITY_EU_{{ env_var('DBT_REGION') }}_PRIVATE
      C2_H22_FINANCE_ORGANIZATION:
        +schema: BTDP_DS_C2_H22_FINANCE_ORGANIZATION_EU_{{ env_var('DBT_REGION') }}_PRIVATE
    publish:
      +on_schema_change: 'sync_all_columns'
      +database: HRDP_SDDS_{{ env_var('DBT_REGION') }}_DB
      C1_H01_ORGANIZATION_STRUCTURE:
        +schema: BTDP_DS_C1_H01_ORGANIZATION_STRUCTURE_EU_{{ env_var('DBT_REGION') }}
      C1_H02_JOB_ARCHITECTURE:
        +schema: BTDP_DS_C1_H02_JOB_ARCHITECTURE_EU_{{ env_var('DBT_REGION') }}
      C1_H03_REWARDS_AND_PAY_STRUCTURE:
        +schema: BTDP_DS_C1_H03_REWARDS_AND_PAY_STRUCTURE_EU_{{ env_var('DBT_REGION') }}
      C1_H04_PERSON:
        +schema: BTDP_DS_C1_H04_PERSON_EU_{{ env_var('DBT_REGION') }}
      C1_H05_EMPLOYMENT_INFORMATION:
        +schema: BTDP_DS_C1_H05_EMPLOYMENT_INFORMATION_EU_{{ env_var('DBT_REGION') }}
      C1_H06_EMPLOYEE_SUBGROUP:
        +schema: BTDP_DS_C1_H06_EMPLOYEE_SUBGROUP_EU_{{ env_var('DBT_REGION') }}
      C1_H07_EVENT_REASON:
        +schema: BTDP_DS_C1_H07_EVENT_REASON_EU_{{ env_var('DBT_REGION') }}
      C1_H08_LEARNING:
        +schema: BTDP_DS_C1_H08_LEARNING_EU_{{ env_var('DBT_REGION') }}
      C1_H09_LOREAL:
        +schema: BTDP_DS_C1_H09_LOREAL_CV_EU_{{ env_var('DBT_REGION') }}
      C1_H10_DOCUMENT_MANAGEMENT:
        +schema: BTDP_DS_C1_H10_DOCUMENT_MANAGEMENT_EU_{{ env_var('DBT_REGION') }}
      C1_H11_LEARNING_KPISS:
        +schema: BTDP_DS_C1_H11_LEARNING_KPISS_EU_{{ env_var('DBT_REGION') }}
      C1_H12_TIME_MANAGEMENT:
        +schema: BTDP_DS_C1_H12_TIME_MANAGEMENT_EU_{{ env_var('DBT_REGION') }}
      C1_H13_OTHER_REFERENTIALS:
        +schema: BTDP_DS_C1_H13_OTHER_REFERENTIALS_EU_{{ env_var('DBT_REGION') }}
      C1_H14_KPI_MEASURES:
        +schema: BTDP_DS_C1_H14_KPI_MEASURES_EU_{{ env_var('DBT_REGION') }}
      C1_H15_REWARDS_INFORMATION:
        +schema: BTDP_DS_C1_H15_REWARDS_INFORMATION_EU_{{ env_var('DBT_REGION') }}
      C1_H16_CSRD:
        +schema: BTDP_DS_C1_H16_CSRD_EU_{{ env_var('DBT_REGION') }}
      C1_H17_GROWTH_PORTFOLIO:
        +schema: BTDP_DS_C1_H17_GROWTH_PORTFOLIO_EU_{{ env_var('DBT_REGION') }}
      C1_H18_ONBOARDING:
        +schema: BTDP_DS_C1_H18_ONBOARDING_EU_{{ env_var('DBT_REGION') }}
      C1_H19_HR_CONTROLING:
        +schema: BTDP_DS_C1_H19_HR_CONTROLING_EU_{{ env_var('DBT_REGION') }}
      C1_H20_ADOPTION:
        +schema: BTDP_DS_C1_H20_ADOPTION_EU_{{ env_var('DBT_REGION') }}
      C1_H21_GENDER_DIVERSITY:
        +schema: BTDP_DS_C1_H21_GENDER_DIVERSITY_EU_{{ env_var('DBT_REGION') }}
      C1_H22_FINANCE_ORGANIZATION:
        +schema: BTDP_DS_C1_H22_FINANCE_ORGANIZATION_EU_{{ env_var('DBT_REGION') }}
      C2_H01_ORGANIZATION_STRUCTURE:
        +schema: BTDP_DS_C2_H01_ORGANIZATION_STRUCTURE_EU_{{ env_var('DBT_REGION') }}
      C2_H02_JOB_ARCHITECTURE:
        +schema: BTDP_DS_C2_H02_JOB_ARCHITECTURE_EU_{{ env_var('DBT_REGION') }}
      C2_H03_REWARDS_AND_PAY_STRUCTURE:
        +schema: BTDP_DS_C2_H03_REWARDS_AND_PAY_STRUCTURE_EU_{{ env_var('DBT_REGION') }}
      C2_H04_PERSON:
        +schema: BTDP_DS_C2_H04_PERSON_EU_{{ env_var('DBT_REGION') }}
      C2_H05_EMPLOYMENT_INFORMATION:
        +schema: BTDP_DS_C2_H05_EMPLOYMENT_INFORMATION_EU_{{ env_var('DBT_REGION') }}
      C2_H06_EMPLOYEE_SUBGROUP:
        +schema: BTDP_DS_C2_H06_EMPLOYEE_SUBGROUP_EU_{{ env_var('DBT_REGION') }}
      C2_H07_EVENT_REASON:
        +schema: BTDP_DS_C2_H07_EVENT_REASON_EU_{{ env_var('DBT_REGION') }}
      C2_H08_LEARNING:
        +schema: BTDP_DS_C2_H08_LEARNING_EU_{{ env_var('DBT_REGION') }}
      C2_H09_LOREAL:
        +schema: BTDP_DS_C2_H09_LOREAL_CV_EU_{{ env_var('DBT_REGION') }}
      C2_H10_DOCUMENT_MANAGEMENT:
        +schema: BTDP_DS_C2_H10_DOCUMENT_MANAGEMENT_EU_{{ env_var('DBT_REGION') }}
      C2_H11_LEARNING_KPISS:
        +schema: BTDP_DS_C2_H11_LEARNING_KPISS_EU_{{ env_var('DBT_REGION') }}
      C2_H12_TIME_MANAGEMENT:
        +schema: BTDP_DS_C2_H12_TIME_MANAGEMENT_EU_{{ env_var('DBT_REGION') }}
      C2_H13_OTHER_REFERENTIALS:
        +schema: BTDP_DS_C2_H13_OTHER_REFERENTIALS_EU_{{ env_var('DBT_REGION') }}
      C2_H14_KPI_MEASURES:
        +schema: BTDP_DS_C2_H14_KPI_MEASURES_EU_{{ env_var('DBT_REGION') }}
      C2_H15_REWARDS_INFORMATION:
        +schema: BTDP_DS_C2_H15_REWARDS_INFORMATION_EU_{{ env_var('DBT_REGION') }}
      C2_H16_CSRD:
        +schema: BTDP_DS_C2_H16_CSRD_EU_{{ env_var('DBT_REGION') }}
      C2_H17_GROWTH_PORTFOLIO:
        +schema: BTDP_DS_C2_H17_GROWTH_PORTFOLIO_EU_{{ env_var('DBT_REGION') }}
      C2_H18_ONBOARDING:
        +schema: BTDP_DS_C2_H18_ONBOARDING_EU_{{ env_var('DBT_REGION') }}
      C2_H19_HR_CONTROLING:
        +schema: BTDP_DS_C2_H19_HR_CONTROLING_EU_{{ env_var('DBT_REGION') }}
      C2_H20_ADOPTION:
        +schema: BTDP_DS_C2_H20_ADOPTION_EU_{{ env_var('DBT_REGION') }}
      C2_H21_GENDER_DIVERSITY:
        +schema: BTDP_DS_C2_H21_GENDER_DIVERSITY_EU_{{ env_var('DBT_REGION') }}
      C2_H22_FINANCE_ORGANIZATION:
        +schema: BTDP_DS_C2_H22_FINANCE_ORGANIZATION_EU_{{ env_var('DBT_REGION') }}
    lrn_staging:
      +database: HRDP_STG_{{ env_var('DBT_REGION') }}_DB
      +schema: SDDS_STG_SCH
    publish_cmn:
      +on_schema_change: 'sync_all_columns'
      +database: HRDP_PUB_{{ env_var('DBT_REGION') }}_DB
      +schema: CMN_PUB_SCH
    publish_ack:
      +on_schema_change: 'sync_all_columns'
      +database: HRDP_PUB_{{ env_var('DBT_REGION') }}_DB
      +schema: ACK_PUB_SCH
    publish_lrn:
      +on_schema_change: 'sync_all_columns'
      +database: HRDP_PUB_{{ env_var('DBT_REGION') }}_DB
      +schema: LRN_PUB_SCH
    views:
      +database: HRDP_PUB_{{ env_var('DBT_REGION') }}_DB
snapshots:
  staging:
  +transient: true
  +target_database: HRDP_STG_{{ env_var('DBT_REGION') }}_DB
  +target_schema: SDDS_STG_SCH
seeds:
  +transient: true
  +database: HRDP_LND_{{ env_var('DBT_REGION') }}_DB
  +schema: SDDS_LND_SCH
tests:
    +severity: error
    error_if: ">10"