select distinct
    ddep_employee_profile_sk_ddep as employee_key,
    ddep_employee_profile_key_ddep as employee_key_v1,
    ddep_employee_id_ddep as employee_id,
    ddep_employee_upn_ddep as employee_upn,
    ddep_first_name_ddep as first_name,
    ddep_last_name_ddep as last_name,
    ddep_email_ddep as email,
    ddep_hire_date_ddep as hire_date,
    ddep_gender_ddep as gender,
    ddep_status_ddep as status,
    ddep_ec_status_ddep as ec_status,
    ddep_location_code_ddep as location_code,
    ddep_location_ddep as location,
    ddep_birth_date_ddep as birth_date,
    ddep_group_seniority_ddep as group_seniority,
    ddep_nationality_ddep as nationality,
    ddep_country_code_ddep as country_code,
    ddep_country_ddep as country,
    zones,
    ddep_job_role_code_ddep as job_role_code,
    ddep_job_role_ddep as job_role,
    ddep_specialization_code_ddep as specialization_code,
    ddep_specialization_ddep as specialization,
    ddep_professional_field_code_ddep as professional_field_code,
    ddep_professional_field_ddep as professional_field,
    ddep_job_seniority_ddep as job_seniority,
    ddep_company_code_ddep as company_code,
    ddep_company_ddep as company,
    ddep_division_code_ddep as division_code,
    ddep_division_ddep as division,
    ddep_bu_type_code_ddep as bu_type_code,
    ddep_bu_type_ddep as bu_type,
    ddep_bu_code_ddep as bu_code,
    ddep_bu_ddep as bu,
    ddep_position_ddep as position,
    plant,
    dc,
    ba,
    intern,
    apprentice,
    departed,
    ddep_ismanager_ddep as ismanager,
    ddep_job_seniority_range_ddep,
    ddep_age_range_ddep,
    ddep_group_seniority_range_ddep,
    all_player_status,
    business_unit,
    ddep_employee_group_ddep
from {{ ref("dim_employee_profile_final") }}
