{% macro create_grant_db_sch() %}

USE ROLE HRDP_{{ env_var('DBT_REGION') }}_DOMAIN_ADMIN;

----------------Create Databases------------------------------
CREATE DATABASE IF NOT EXISTS HRDP_QCK_{{ env_var('DBT_REGION') }}_DB; 

--USE DATABASE HRDP_LND_{{ env_var('DBT_REGION') }}_DB;
USE DATABASE HRDP_QCK_{{ env_var('DBT_REGION') }}_DB;

CREATE SCHEMA IF NOT EXISTS QCK_{{ env_var('DBT_REGION') }}_SCH WITH MANAGED ACCESS;

CREATE TABLE IF NOT EXISTS HRDP_QCK_{{ env_var('DBT_REGION') }}_DB.QCK_{{ env_var('DBT_REGION') }}_SCH.DIM_PARAM_DATAQUALITY_QUERIES (
	RULE_ID NUMBER(38,0),
	FAMILLY VARCHAR(100) COLLATE 'en-ci',
	SUB_FAMILLY VARCHAR(100) COLLATE 'en-ci',
	BOA_COLLIBRA VARCHAR(100) COLLATE 'en-ci',
	BOA_ID_COLLIBRA VARCHAR(100) COLLATE 'en-ci',
	AUDITED_QUALITY_DIMENSION VARCHAR(100) COLLATE 'en-ci',
	QUALITY_PURPOSE VARCHAR(100) COLLATE 'en-ci',
	BONUS VARCHAR(3) COLLATE 'en-ci',
	QUALITY_RULE_ID VARCHAR(100) COLLATE 'en-ci',
	QUALITY_RULE_NAME VARCHAR(100) COLLATE 'en-ci',
	RULE_DESCRIPTION VARCHAR(1000) COLLATE 'en-ci',
	FORMULA_CODE_SQL VARCHAR(16777216) COLLATE 'en-ci',
	TARGET VARCHAR(100) COLLATE 'en-ci',
	RLS VARCHAR(100) COLLATE 'en-ci',
	STATUS VARCHAR(100) COLLATE 'en-ci',
	UPN VARCHAR(100) COLLATE 'en-ci',
	CREATION_DATE TIMESTAMP_LTZ(9),
	MODIFICATION_DATE TIMESTAMP_LTZ(9)
);
 
CREATE TABLE IF NOT EXISTS HRDP_QCK_{{ env_var('DBT_REGION') }}_DB.QCK_{{ env_var('DBT_REGION') }}_SCH.DIM_ORGANIZATION (
	BUSINESS_UNIT_PK NUMBER(18,0),
	BUSINESS_UNIT_CODE VARCHAR(16777216) COLLATE 'en-ci',
	BUSINESS_UNIT_NAME VARCHAR(16777216) COLLATE 'en-ci',
	COMPANY_CODE VARCHAR(16777216) COLLATE 'en-ci',
	COMPANY_NAME VARCHAR(16777216) COLLATE 'en-ci',
	COUNTRY_CODE VARCHAR(16777216) COLLATE 'en-ci',
	COUNTRY_NAME VARCHAR(16777216) COLLATE 'en-ci',
	GEOGRAPHIC_ZONE_CODE VARCHAR(16777216) COLLATE 'en-ci',
	GEOGRAPHIC_ZONE VARCHAR(16777216) COLLATE 'en-ci',
	HR_DIVISION_CODE VARCHAR(16777216) COLLATE 'en-ci',
	HR_DIVISION_NAME VARCHAR(16777216) COLLATE 'en-ci'
);
 
CREATE TABLE IF NOT EXISTS HRDP_QCK_{{ env_var('DBT_REGION') }}_DB.QCK_{{ env_var('DBT_REGION') }}_SCH.DIM_PROFESSIONAL_FIELD (
	PROFESSIONAL_FIELD_PK NUMBER(18,0),
	PROFESSIONAL_FIELD_CODE VARCHAR(16777216) COLLATE 'en-ci',
	PROFESSIONAL_FIELD_NAME VARCHAR(16777216) COLLATE 'en-ci'
);


CREATE TABLE IF NOT EXISTS HRDP_QCK_{{ env_var('DBT_REGION') }}_DB.QCK_{{ env_var('DBT_REGION') }}_SCH.FACT_DATAQUALITY_RESULTS cluster by (run_id )(
	RUN_ID NUMBER(38,0),
	RULE_ID NUMBER(38,0),
	SUBJECT_DOMAIN VARCHAR(16777216) COLLATE 'en-ci',
	BUSINESS_UNIT_CODE VARCHAR(50) COLLATE 'en-ci',
	PROFESSIONAL_FIELD_CODE VARCHAR(50) COLLATE 'en-ci',
	BUSINESS_UNIT_PK NUMBER(38,0),
	PROFESSIONAL_FIELD_PK NUMBER(38,0),
	USER_ID VARCHAR(40) COLLATE 'en-ci',
	ROW_ID NUMBER(38,0),
	COLUMN_NAME VARCHAR(250) COLLATE 'en-ci',
	COLUMN_VALUE VARCHAR(250) COLLATE 'en-ci'
) WITH ROW ACCESS POLICY HRDP_QCK_{{ env_var('DBT_REGION') }}_DB.QCK_{{ env_var('DBT_REGION') }}_SCH.QCK_RLS_POL ON (USER_ID, SUBJECT_DOMAIN)
;


CREATE TABLE IF NOT EXISTS HRDP_QCK_{{ env_var('DBT_REGION') }}_DB.QCK_{{ env_var('DBT_REGION') }}_SCH.FACT_DATAQUALITY_RESULTS_HISTO (
	RUN_ID NUMBER(38,0),
	RULE_ID NUMBER(38,0),
	SUBJECT_DOMAIN VARCHAR(16777216) COLLATE 'en-ci',
	BUSINESS_UNIT_CODE VARCHAR(50) COLLATE 'en-ci',
	PROFESSIONAL_FIELD_CODE VARCHAR(50) COLLATE 'en-ci',
	BUSINESS_UNIT_PK NUMBER(38,0),
	PROFESSIONAL_FIELD_PK NUMBER(38,0),
	USER_ID VARCHAR(40) COLLATE 'en-ci',
	ROW_ID NUMBER(38,0),
	COLUMN_NAME VARCHAR(250) COLLATE 'en-ci',
	COLUMN_VALUE VARCHAR(250) COLLATE 'en-ci'
);


CREATE TABLE IF NOT EXISTS HRDP_QCK_{{ env_var('DBT_REGION') }}_DB.QCK_{{ env_var('DBT_REGION') }}_SCH.LOG_DATAQUALITY_RUNS (
	RUN_ID NUMBER(38,0),
	START_DATE TIMESTAMP_LTZ(9),
	END_DATE TIMESTAMP_LTZ(9),
	STATUS VARCHAR(20) COLLATE 'en-ci',
	MESSAGE VARCHAR(16777216) COLLATE 'en-ci',
	DATE_SK NUMBER(38,0)
);


CREATE TABLE IF NOT EXISTS HRDP_QCK_{{ env_var('DBT_REGION') }}_DB.QCK_{{ env_var('DBT_REGION') }}_SCH.LOG_DATA_QUALITY_BY_RULE (
	RUN_ID NUMBER(38,0),
	RULE_ID NUMBER(38,0),
	SUBJECT_DOMAIN VARCHAR(16777216) COLLATE 'en-ci',
	BUSINESS_UNIT_CODE VARCHAR(50) COLLATE 'en-ci',
	PROFESSIONAL_FIELD_CODE VARCHAR(50) COLLATE 'en-ci',
	BUSINESS_UNIT_PK NUMBER(38,0),
	PROFESSIONAL_FIELD_PK NUMBER(38,0),
	ERROR_COUNT NUMBER(38,0),
	TOTAL_COUNT NUMBER(38,0)
) WITH ROW ACCESS POLICY HRDP_QCK_{{ env_var('DBT_REGION') }}_DB.QCK_{{ env_var('DBT_REGION') }}_SCH.QCK_RLS_LOGDATA_POL ON (BUSINESS_UNIT_CODE, PROFESSIONAL_FIELD_CODE, SUBJECT_DOMAIN)
;
 {% endmacro %}