{{
    config(
        materialized="incremental",
        unique_key="1",
        transient=false,
        incremental_strategy="delete+insert",
        on_schema_change="sync_all_columns",
    )
}}
WITH GOALS_UPDATE AS (
    SELECT DISTINCT FPGU_GOAL_PLAN_ID_DPGP
      ,FPGU_PERF_GOAL_KEY_DPPG
      ,FPPG_EMPLOYEE_KEY_DDEP
      ,FPPG_CATEGORY_KEY_DPGC
      ,FPPG_STATUS_DPGS
      ,FPPG_PERF_GOALS_CASCADED_KEY_DPGS
      ,FPPG_PERF_GOALS_TYPE_KEY_DPGT
      ,FPGU_IS_CURRENT_SITUATION_FPGU
      ,FPGU_PREVIOUS_GOAL_NAME_FPGU
      ,FPGU_UPDATED_GOAL_NAME_FPGU
      ,FPGU_PREVIOUS_KPI_NAME_FPGU
      ,FPGU_UPDATED_KPI_NAME_FPGU
      ,FPGU_UPDATE_DATE_FPGU
      ,FPPG_FG_DELETED_FPPG
      ,collate(CASE 
        WHEN DPGP_YEAR_DPGP = YEAR(FPGU_UPDATE_DATE_FPGU)
          THEN RIGHT('0' || Cast(MONTH(FPGU_UPDATE_DATE_FPGU) AS VARCHAR(4)), 2)
        WHEN DPGP_YEAR_DPGP > YEAR(FPGU_UPDATE_DATE_FPGU)
          THEN '.Prev Years'
        WHEN DPGP_YEAR_DPGP < YEAR(FPGU_UPDATE_DATE_FPGU)
          THEN 'Next Years'
        END,'en-ci') AS UPDATE_DATE_MONTH_DISPLAY
    FROM {{ ref('fact_perf_goals_update') }}
    INNER JOIN {{ ref('fact_perf_goals') }} ON FPGU_PERF_GOAL_KEY_DPPG = FPPG_PERF_GOAL_KEY_DPPG
    INNER JOIN {{ ref('dim_perf_goal_plan') }} on DPGP_GOAL_PLAN_ID_DPGP = FPPG_GOAL_PLAN_ID_FPPG
    JOIN {{ ref('dim_perf_goals_category_vw') }} ON GOAL_CATEGORY_KEY = FPPG_CATEGORY_KEY_DPGC
    WHERE (FPPG_FG_DELETED_FPPG = 'Active' or FPPG_FG_DELETED_FPPG is null)
      AND GOAL_CATEGORY_LABEL <> 'Archive'
    )

SELECT FPGU_GOAL_PLAN_ID_DPGP
  ,FPGU_PERF_GOAL_KEY_DPPG
  ,FPPG_EMPLOYEE_KEY_DDEP
  ,FPPG_CATEGORY_KEY_DPGC
  ,FPPG_STATUS_DPGS
  ,FPPG_PERF_GOALS_CASCADED_KEY_DPGS
  ,FPPG_PERF_GOALS_TYPE_KEY_DPGT
  ,FPGU_IS_CURRENT_SITUATION_FPGU
  ,FPGU_PREVIOUS_GOAL_NAME_FPGU
  ,FPGU_UPDATED_GOAL_NAME_FPGU
  ,FPGU_PREVIOUS_KPI_NAME_FPGU
  ,FPGU_UPDATED_KPI_NAME_FPGU
  ,FPGU_UPDATE_DATE_FPGU
  ,FPPG_FG_DELETED_FPPG
  ,UPDATE_DATE_MONTH_DISPLAY
FROM GOALS_UPDATE