{{ config(materialized = 'table', transient = false) }}
WITH USER_DETAILS AS (
		SELECT USER_ID
			,GOAL_ID
			,GOAL_NAME
			,CATEGORY
			,GOAL_STATUS
			,PURPOSE_LABEL
			,PURPOSE
			,GOAL_MODIFIER
			,GOAL_OWNER
			,LAST_MODIFIED_DATE
			,DUE_DATE
			,COUNT(DISTINCT GOAL_ID) OVER (PARTITION BY USER_ID) AS NB_EMPLOYEE_GOALS
            ,DEV_GOAL_TEMPLATE_ID
		FROM (select * from {{ ref('stg_user_dev_goal_details_flatten') }} where DBT_VALID_TO is null)
		)

SELECT USER_ID
	,GOAL_ID
	,GOAL_NAME
	,CATEGORY
	,GOAL_STATUS
	,PURPOSE_LABEL
	,PURPOSE
	,GOAL_MODIFIER
	,GOAL_OWNER
	,LAST_MODIFIED_DATE
	,DUE_DATE
	,NB_EMPLOYEE_GOALS
    ,DEV_GOAL_TEMPLATE_ID
FROM USER_DETAILS