{{ config(materialized = 'table', transient = false) }}
WITH DEV_REPORT AS (
		SELECT distinct
			 DEVELOPMENT_GOAL_ID
             ,GOAL_NAME
			,GOAL_ACTIVE_DELETED
            ,CREATED_DATE
			,ACTIVITY_ID
			,ACTIVITY_NAME
			,ACTIVITY_LAST_MODIFICATION_DATE
            ,LEARNING_ACTIVITY_ID
            ,LEARNING_STATUS
            ,IS_GLA_ACTIVE
            ,COUNT(DISTINCT ACTIVITY_ID) OVER (PARTITION BY DEVELOPMENT_GOAL_ID) AS NB_ACTIVITIES_PER_GOAL
            ,COUNT(DISTINCT LEARNING_ACTIVITY_ID) OVER (PARTITION BY DEVELOPMENT_GOAL_ID) AS NB_LINKED_LEARNING_GOALS 
		FROM {{ ref('stg_dev_goal_report') }} )
				
        

             SELECT 
			DEVELOPMENT_GOAL_ID
             ,GOAL_NAME
			,GOAL_ACTIVE_DELETED
            ,CREATED_DATE
			,ACTIVITY_ID
			,ACTIVITY_NAME
			,ACTIVITY_LAST_MODIFICATION_DATE
            ,LEARNING_ACTIVITY_ID
            ,LEARNING_STATUS
            ,IS_GLA_ACTIVE
			,NB_ACTIVITIES_PER_GOAL
			,NB_LINKED_LEARNING_GOALS
FROM DEV_REPORT