# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'HRDP'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'default'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.

models:
  HRDP:
    tables:
      +materialization : table
      +database: |
          {%- if  target.name == "DV" -%} HRDP_PUB_DV_DB
          {%- elif  target.name == "QA" -%} HRDP_PUB_QA_DB
          {%- elif  target.name == "NP" -%} HRDP_PUB_NP_DB
          {%- elif  target.name == "PD" -%} HRDP_PUB_PD_DB
          {%- else  -%} HRDP_PUB_DV_DB
          {%- endif -%}
      +schema: |
          {%- if  target.name == "IDE" -%} {{target.schema}}
          {%- else  -%} QCK_PUB_SCH
          {%- endif -%}
    views:
      +materialization : views
      +database: |
          {%- if  target.name == "DV" -%} HRDP_PUB_DV_DB
          {%- elif  target.name == "QA" -%} HRDP_PUB_QA_DB
          {%- elif  target.name == "NP" -%} HRDP_PUB_NP_DB
          {%- elif  target.name == "PD" -%} HRDP_PUB_PD_DB
          {%- else  -%} HRDP_PUB_DV_DB
          {%- endif -%}
      +schema: |
          {%- if  target.name == "IDE" -%} {{target.schema}}
          {%- else  -%} QCK_PUB_SCH
          {%- endif -%}
    rls:
      +materialization : table
      +database: |
          {%- if  target.name == "DV" -%} HRDP_QCK_DV_DB
          {%- elif  target.name == "QA" -%} HRDP_QCK_QA_DB
          {%- elif  target.name == "NP" -%} HRDP_QCK_NP_DB
          {%- elif  target.name == "PD" -%} HRDP_QCK_PD_DB
          {%- else  -%} HRDP_QCK_DV_DB
          {%- endif -%}
      +schema: |
          {%- if  target.name == "IDE" -%} {{target.schema}}
          {%- else  -%} CMN_CORE_SCH
          {%- endif -%}
tests:
    +severity: error
    error_if: ">1000"