{{ config(materialized='table',transient=false) }}

with GOAL_REPORT_INT
AS
(
 SELECT 
 CREATED_BY_USERNAME,
 GOAL_ID,
 GOAL_PLAN_ID,
 GOAL_ALIGNED_UP,
 DUE_DATE,
 CREATED_DATE,
 ACTIVE_DELETED,
 COUNT(Distinct ACTIVITY_ID) AS NB_ACTIVITIES_PER_GOAL_ID 
 FROM {{ ref('stg_perf_goal_report') }}
 GROUP BY CREATED_BY_USERNAME,GOAL_ID,GOAL_ALIGNED_UP,DUE_DATE,CREATED_DATE,ACTIVE_DELETED,GOAL_PLAN_ID
)
SELECT
CREATED_BY_USERNAME,
 GOAL_ID,
 GOAL_PLAN_ID,
 GOAL_ALIGNED_UP,
 DUE_DATE,
 CREATED_DATE,
 ACTIVE_DELETED,
 NB_ACTIVITIES_PER_GOAL_ID
 from GOAL_REPORT_INT