{{ config(materialized="table", transient=false,
post_hook= 
"CREATE OR REPLACE TABLE  {{ env_var('DBT_US_DB') }}.{{ env_var('DBT_US_SCHEMA') }}.DIM_SF_ROLES_GROUP AS
SELECT * FROM {{ env_var('DBT_CORE_DB') }}.CMN_CORE_SCH.DIM_SF_ROLES_GROUP;
CREATE OR REPLACE TABLE  {{ env_var('DBT_US_DB') }}.{{ env_var('DBT_US_SCHEMA') }}.DIM_GROUP_USER AS
SELECT * FROM {{ env_var('DBT_CORE_DB') }}.CMN_CORE_SCH.DIM_GROUP_USER;
CREATE OR REPLACE TABLE  {{ env_var('DBT_US_DB') }}.{{ env_var('DBT_US_SCHEMA') }}.DIM_USER_UPN AS
select DDEP_EMPLOYEE_ID_DDEP as EMPLOYEE_ID,DDEP_UPN_DDEP as EMPLOYEE_UPN 
from {{ env_var('DBT_STAGING_DB') }}.CMN_STG_SCH.STG_EMPLOYEE_PROFILE_FLATTEN;
DROP TABLE {{ env_var('DBT_CORE_DB') }}.CMN_CORE_SCH.DIM_RLS_US_TABLE_CREATION;
"

) }}

SELECT * FROM DUAL
