{% macro assign_prfl() %}
    {% set query %}

     USE ROLE HRDP_{{ env_var('DBT_REGION') }}_DOMAIN_ADMIN;
        ----------------Create Databases------------------------------
        USE DATABASE HRDP_SDDS_{{ env_var('DBT_REGION') }}_DB; 
        --------------------Create Schema---------------------
        USE SCHEMA BTDP_DS_C1_H08_LEARNING_EU_{{ env_var('DBT_REGION') }}_PRIVATE;

        ------- the below update statement ran as per the simon request and it is completed as part of sprint 22 --
        -- update DIM_PARAM_ASSIGNMENT_PROFILE_REFERENTIAL
        -- set ASSIGNMENT_PROFILE_ID='AP_JBMUST_THEWAYWEWORKWITHOURSUPPLIERS_TARGET'
        -- where ASSIGNMENT_PROFILE_ID='AP_JBMUST_THE_WAY_WE_WORK_WITH_OUR_SUPPLIERS_TARGET';
         
         -- newly added statement as part of ticket STRY0290258 

ALTER TABLE DIM_PARAM_ASSIGNMENT_PROFILE_REFERENTIAL
ADD COLUMN ASSIGNMENT_PROFILE_CATEGORY_CODE VARCHAR;

ALTER TABLE DIM_PARAM_ASSIGNMENT_PROFILE_REFERENTIAL
ADD COLUMN ASSIGNMENT_PROFILE_CATEGORY_NAME VARCHAR;

UPDATE DIM_PARAM_ASSIGNMENT_PROFILE_REFERENTIAL
SET ASSIGNMENT_PROFILE_CATEGORY_CODE='BUSINESSMUST',ASSIGNMENT_PROFILE_CATEGORY_NAME='Business Must'
where ASSIGNMENT_PROFILE_ID in ('AP_BUSINESSMUST_GST_TARGET','AP_BUSINESSMUST_DATA4ALL_TARGET');

UPDATE DIM_PARAM_ASSIGNMENT_PROFILE_REFERENTIAL
SET ASSIGNMENT_PROFILE_CATEGORY_CODE='JBMUST',ASSIGNMENT_PROFILE_CATEGORY_NAME='Job Must'
where ASSIGNMENT_PROFILE_ID 
in ('AP_JBMUST_THEWAYWEWORKWITHOURSUPPLIERS_TARGET','AP_JBMUST_ACD_INTRODUCTION_TO_RGM_@_ACD_TARGET','AP_JOBMUST_COMMERCE_ESSENTIALS_TARGET');

        {% endset %}

    {% do run_query(query) %}

{% endmacro %}    