{% macro create_grant_dq_allgen() %}
    {% set query %}
        USE ROLE HRDP_{{ env_var('DBT_REGION') }}_DOMAIN_ADMIN;
        USE DATABASE HRDP_DATAQUALITY_{{ env_var('DBT_REGION') }}_DB;		
		--------------------Create Schema---------------------
        CREATE SCHEMA IF NOT EXISTS ALLGEN_SCH WITH MANAGED ACCESS;
        --------------------Grant Usage on Schema---------------------
        GRANT USAGE ON SCHEMA ALLGEN_SCH TO ROLE _TECH_DQ_{{ env_var('DBT_REGION') }}_RO_ROLE;
        GRANT ALL PRIVILEGES ON SCHEMA ALLGEN_SCH TO ROLE _TECH_DQ_{{ env_var('DBT_REGION') }}_OWN_ROLE;
        -----------Grants for current Object---------
        GRANT SELECT ON ALL TABLES IN SCHEMA ALLGEN_SCH TO ROLE _TECH_DQ_{{ env_var('DBT_REGION') }}_RO_ROLE;
        GRANT SELECT ON ALL VIEWS IN SCHEMA ALLGEN_SCH TO ROLE _TECH_DQ_{{ env_var('DBT_REGION') }}_RO_ROLE;
        GRANT USAGE, READ ON ALL STAGES IN SCHEMA ALLGEN_SCH TO ROLE _TECH_DQ_{{ env_var('DBT_REGION') }}_RO_ROLE;
        GRANT USAGE ON ALL FILE FORMATS IN SCHEMA ALLGEN_SCH TO ROLE _TECH_DQ_{{ env_var('DBT_REGION') }}_RO_ROLE;
        GRANT SELECT ON ALL STREAMS IN SCHEMA ALLGEN_SCH TO ROLE _TECH_DQ_{{ env_var('DBT_REGION') }}_RO_ROLE;
        GRANT USAGE ON ALL FUNCTIONS IN SCHEMA ALLGEN_SCH TO ROLE _TECH_DQ_{{ env_var('DBT_REGION') }}_RO_ROLE;
        -----------Grants for Future Object---------
        GRANT SELECT ON FUTURE TABLES IN SCHEMA ALLGEN_SCH TO ROLE _TECH_DQ_{{ env_var('DBT_REGION') }}_RO_ROLE;
        GRANT SELECT ON FUTURE VIEWS IN SCHEMA ALLGEN_SCH TO ROLE _TECH_DQ_{{ env_var('DBT_REGION') }}_RO_ROLE;
        GRANT USAGE, READ ON FUTURE STAGES IN SCHEMA ALLGEN_SCH TO ROLE _TECH_DQ_{{ env_var('DBT_REGION') }}_RO_ROLE;
        GRANT USAGE ON FUTURE FILE FORMATS IN SCHEMA ALLGEN_SCH TO ROLE _TECH_DQ_{{ env_var('DBT_REGION') }}_RO_ROLE;
        GRANT SELECT ON FUTURE STREAMS IN SCHEMA ALLGEN_SCH TO ROLE _TECH_DQ_{{ env_var('DBT_REGION') }}_RO_ROLE;
        GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA ALLGEN_SCH TO ROLE _TECH_DQ_{{ env_var('DBT_REGION') }}_RO_ROLE;
        GRANT USAGE ON FUTURE FUNCTIONS IN SCHEMA ALLGEN_SCH TO ROLE _TECH_DQ_{{ env_var('DBT_REGION') }}_RO_ROLE;
        -----------Grant Privileges to Technical Ownership roles---------
        GRANT OWNERSHIP ON ALL TABLES IN SCHEMA ALLGEN_SCH TO ROLE _TECH_DQ_{{ env_var('DBT_REGION') }}_OWN_ROLE;
        GRANT OWNERSHIP ON ALL VIEWS IN SCHEMA ALLGEN_SCH TO ROLE _TECH_DQ_{{ env_var('DBT_REGION') }}_OWN_ROLE;
        GRANT OWNERSHIP ON ALL STAGES IN SCHEMA ALLGEN_SCH TO ROLE _TECH_DQ_{{ env_var('DBT_REGION') }}_OWN_ROLE;
        GRANT OWNERSHIP ON ALL FILE FORMATS IN SCHEMA ALLGEN_SCH TO ROLE _TECH_DQ_{{ env_var('DBT_REGION') }}_OWN_ROLE;
        GRANT OWNERSHIP ON ALL STREAMS IN SCHEMA ALLGEN_SCH TO ROLE _TECH_DQ_{{ env_var('DBT_REGION') }}_OWN_ROLE;
        GRANT OWNERSHIP ON ALL PROCEDURES IN SCHEMA ALLGEN_SCH TO ROLE _TECH_DQ_{{ env_var('DBT_REGION') }}_OWN_ROLE;
        GRANT OWNERSHIP ON ALL FUNCTIONS IN SCHEMA ALLGEN_SCH TO ROLE _TECH_DQ_{{ env_var('DBT_REGION') }}_OWN_ROLE;
        GRANT OWNERSHIP ON ALL SEQUENCES IN SCHEMA ALLGEN_SCH TO ROLE _TECH_DQ_{{ env_var('DBT_REGION') }}_OWN_ROLE;
        GRANT OWNERSHIP ON ALL TASKS IN SCHEMA ALLGEN_SCH TO ROLE _TECH_DQ_{{ env_var('DBT_REGION') }}_OWN_ROLE;
        -----------Grants For Future Object---------
        GRANT OWNERSHIP ON FUTURE TABLES IN SCHEMA ALLGEN_SCH TO ROLE _TECH_DQ_{{ env_var('DBT_REGION') }}_OWN_ROLE;
        GRANT OWNERSHIP ON FUTURE VIEWS IN SCHEMA ALLGEN_SCH TO ROLE _TECH_DQ_{{ env_var('DBT_REGION') }}_OWN_ROLE;
        GRANT OWNERSHIP ON FUTURE STAGES IN SCHEMA ALLGEN_SCH TO ROLE _TECH_DQ_{{ env_var('DBT_REGION') }}_OWN_ROLE;
        GRANT OWNERSHIP ON FUTURE FILE FORMATS IN SCHEMA ALLGEN_SCH TO ROLE _TECH_DQ_{{ env_var('DBT_REGION') }}_OWN_ROLE;
        GRANT OWNERSHIP ON FUTURE STREAMS IN SCHEMA ALLGEN_SCH TO ROLE _TECH_DQ_{{ env_var('DBT_REGION') }}_OWN_ROLE;
        GRANT OWNERSHIP ON FUTURE PROCEDURES IN SCHEMA ALLGEN_SCH TO ROLE _TECH_DQ_{{ env_var('DBT_REGION') }}_OWN_ROLE;
        GRANT OWNERSHIP ON FUTURE FUNCTIONS IN SCHEMA ALLGEN_SCH TO ROLE _TECH_DQ_{{ env_var('DBT_REGION') }}_OWN_ROLE;
        GRANT OWNERSHIP ON FUTURE SEQUENCES IN SCHEMA ALLGEN_SCH TO ROLE _TECH_DQ_{{ env_var('DBT_REGION') }}_OWN_ROLE;
        GRANT OWNERSHIP ON FUTURE TASKS IN SCHEMA ALLGEN_SCH TO ROLE _TECH_DQ_{{ env_var('DBT_REGION') }}_OWN_ROLE;

    {% endset %}

    {% do run_query(query) %}

{% endmacro %}