{% macro create_grant_db_h14_kpi() %}
    {% set query %}
        -------------- Execute below statement using DOMAIN_ADMIN role ---------
        USE ROLE HRDP_{{ env_var('DBT_REGION') }}_DOMAIN_ADMIN;
        ----------------Create Databases------------------------------
        CREATE DATABASE IF NOT EXISTS HRDP_SDDS_{{ env_var('DBT_REGION') }}_DB;
        USE DATABASE HRDP_SDDS_{{ env_var('DBT_REGION') }}_DB;
        ------------------------------------------------------------------------
        
        --------------------Create Schema---------------------
        CREATE SCHEMA IF NOT EXISTS BTDP_DS_C1_H14_KPI_MEASURES_EU_{{ env_var('DBT_REGION') }} WITH MANAGED ACCESS;
        --------------------Grant Usage on Schema---------------------
        GRANT USAGE ON SCHEMA BTDP_DS_C1_H14_KPI_MEASURES_EU_{{ env_var('DBT_REGION') }} TO ROLE _TECH_SDDS_{{ env_var('DBT_REGION') }}_RO_ROLE;
        GRANT ALL PRIVILEGES ON SCHEMA BTDP_DS_C1_H14_KPI_MEASURES_EU_{{ env_var('DBT_REGION') }} TO ROLE _TECH_SDDS_{{ env_var('DBT_REGION') }}_OWN_ROLE;
        -----------Grants for current Object---------
        GRANT SELECT ON ALL TABLES IN SCHEMA BTDP_DS_C1_H14_KPI_MEASURES_EU_{{ env_var('DBT_REGION') }} TO ROLE _TECH_SDDS_{{ env_var('DBT_REGION') }}_RO_ROLE;
        GRANT SELECT ON ALL VIEWS IN SCHEMA BTDP_DS_C1_H14_KPI_MEASURES_EU_{{ env_var('DBT_REGION') }} TO ROLE _TECH_SDDS_{{ env_var('DBT_REGION') }}_RO_ROLE;
        GRANT USAGE, READ ON ALL STAGES IN SCHEMA BTDP_DS_C1_H14_KPI_MEASURES_EU_{{ env_var('DBT_REGION') }} TO ROLE _TECH_SDDS_{{ env_var('DBT_REGION') }}_RO_ROLE;
        GRANT USAGE ON ALL FILE FORMATS IN SCHEMA BTDP_DS_C1_H14_KPI_MEASURES_EU_{{ env_var('DBT_REGION') }} TO ROLE _TECH_SDDS_{{ env_var('DBT_REGION') }}_RO_ROLE;
        GRANT SELECT ON ALL STREAMS IN SCHEMA BTDP_DS_C1_H14_KPI_MEASURES_EU_{{ env_var('DBT_REGION') }} TO ROLE _TECH_SDDS_{{ env_var('DBT_REGION') }}_RO_ROLE;
        GRANT USAGE ON ALL FUNCTIONS IN SCHEMA BTDP_DS_C1_H14_KPI_MEASURES_EU_{{ env_var('DBT_REGION') }} TO ROLE _TECH_SDDS_{{ env_var('DBT_REGION') }}_RO_ROLE;
        -----------Grants for Future Object---------
        GRANT SELECT ON FUTURE TABLES IN SCHEMA BTDP_DS_C1_H14_KPI_MEASURES_EU_{{ env_var('DBT_REGION') }} TO ROLE _TECH_SDDS_{{ env_var('DBT_REGION') }}_RO_ROLE;
        GRANT SELECT ON FUTURE VIEWS IN SCHEMA BTDP_DS_C1_H14_KPI_MEASURES_EU_{{ env_var('DBT_REGION') }} TO ROLE _TECH_SDDS_{{ env_var('DBT_REGION') }}_RO_ROLE;
        GRANT USAGE, READ ON FUTURE STAGES IN SCHEMA BTDP_DS_C1_H14_KPI_MEASURES_EU_{{ env_var('DBT_REGION') }} TO ROLE _TECH_SDDS_{{ env_var('DBT_REGION') }}_RO_ROLE;
        GRANT USAGE ON FUTURE FILE FORMATS IN SCHEMA BTDP_DS_C1_H14_KPI_MEASURES_EU_{{ env_var('DBT_REGION') }} TO ROLE _TECH_SDDS_{{ env_var('DBT_REGION') }}_RO_ROLE;
        GRANT SELECT ON FUTURE STREAMS IN SCHEMA BTDP_DS_C1_H14_KPI_MEASURES_EU_{{ env_var('DBT_REGION') }} TO ROLE _TECH_SDDS_{{ env_var('DBT_REGION') }}_RO_ROLE;
        GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA BTDP_DS_C1_H14_KPI_MEASURES_EU_{{ env_var('DBT_REGION') }} TO ROLE _TECH_SDDS_{{ env_var('DBT_REGION') }}_RO_ROLE;
        GRANT USAGE ON FUTURE FUNCTIONS IN SCHEMA BTDP_DS_C1_H14_KPI_MEASURES_EU_{{ env_var('DBT_REGION') }} TO ROLE _TECH_SDDS_{{ env_var('DBT_REGION') }}_RO_ROLE;
        -----------Grant Privileges to Technical Ownership roles---------
        GRANT OWNERSHIP ON ALL TABLES IN SCHEMA BTDP_DS_C1_H14_KPI_MEASURES_EU_{{ env_var('DBT_REGION') }} TO ROLE _TECH_SDDS_{{ env_var('DBT_REGION') }}_OWN_ROLE;
        GRANT OWNERSHIP ON ALL VIEWS IN SCHEMA BTDP_DS_C1_H14_KPI_MEASURES_EU_{{ env_var('DBT_REGION') }} TO ROLE _TECH_SDDS_{{ env_var('DBT_REGION') }}_OWN_ROLE;
        GRANT OWNERSHIP ON ALL STAGES IN SCHEMA BTDP_DS_C1_H14_KPI_MEASURES_EU_{{ env_var('DBT_REGION') }} TO ROLE _TECH_SDDS_{{ env_var('DBT_REGION') }}_OWN_ROLE;
        GRANT OWNERSHIP ON ALL FILE FORMATS IN SCHEMA BTDP_DS_C1_H14_KPI_MEASURES_EU_{{ env_var('DBT_REGION') }} TO ROLE _TECH_SDDS_{{ env_var('DBT_REGION') }}_OWN_ROLE;
        GRANT OWNERSHIP ON ALL STREAMS IN SCHEMA BTDP_DS_C1_H14_KPI_MEASURES_EU_{{ env_var('DBT_REGION') }} TO ROLE _TECH_SDDS_{{ env_var('DBT_REGION') }}_OWN_ROLE;
        GRANT OWNERSHIP ON ALL PROCEDURES IN SCHEMA BTDP_DS_C1_H14_KPI_MEASURES_EU_{{ env_var('DBT_REGION') }} TO ROLE _TECH_SDDS_{{ env_var('DBT_REGION') }}_OWN_ROLE;
        GRANT OWNERSHIP ON ALL FUNCTIONS IN SCHEMA BTDP_DS_C1_H14_KPI_MEASURES_EU_{{ env_var('DBT_REGION') }} TO ROLE _TECH_SDDS_{{ env_var('DBT_REGION') }}_OWN_ROLE;
        GRANT OWNERSHIP ON ALL SEQUENCES IN SCHEMA BTDP_DS_C1_H14_KPI_MEASURES_EU_{{ env_var('DBT_REGION') }} TO ROLE _TECH_SDDS_{{ env_var('DBT_REGION') }}_OWN_ROLE;
        GRANT OWNERSHIP ON ALL TASKS IN SCHEMA BTDP_DS_C1_H14_KPI_MEASURES_EU_{{ env_var('DBT_REGION') }} TO ROLE _TECH_SDDS_{{ env_var('DBT_REGION') }}_OWN_ROLE;
        -----------Grants For Future Object---------
        GRANT OWNERSHIP ON FUTURE TABLES IN SCHEMA BTDP_DS_C1_H14_KPI_MEASURES_EU_{{ env_var('DBT_REGION') }} TO ROLE _TECH_SDDS_{{ env_var('DBT_REGION') }}_OWN_ROLE;
        GRANT OWNERSHIP ON FUTURE VIEWS IN SCHEMA BTDP_DS_C1_H14_KPI_MEASURES_EU_{{ env_var('DBT_REGION') }} TO ROLE _TECH_SDDS_{{ env_var('DBT_REGION') }}_OWN_ROLE;
        GRANT OWNERSHIP ON FUTURE STAGES IN SCHEMA BTDP_DS_C1_H14_KPI_MEASURES_EU_{{ env_var('DBT_REGION') }} TO ROLE _TECH_SDDS_{{ env_var('DBT_REGION') }}_OWN_ROLE;
        GRANT OWNERSHIP ON FUTURE FILE FORMATS IN SCHEMA BTDP_DS_C1_H14_KPI_MEASURES_EU_{{ env_var('DBT_REGION') }} TO ROLE _TECH_SDDS_{{ env_var('DBT_REGION') }}_OWN_ROLE;
        GRANT OWNERSHIP ON FUTURE STREAMS IN SCHEMA BTDP_DS_C1_H14_KPI_MEASURES_EU_{{ env_var('DBT_REGION') }} TO ROLE _TECH_SDDS_{{ env_var('DBT_REGION') }}_OWN_ROLE;
        GRANT OWNERSHIP ON FUTURE PROCEDURES IN SCHEMA BTDP_DS_C1_H14_KPI_MEASURES_EU_{{ env_var('DBT_REGION') }} TO ROLE _TECH_SDDS_{{ env_var('DBT_REGION') }}_OWN_ROLE;
        GRANT OWNERSHIP ON FUTURE FUNCTIONS IN SCHEMA BTDP_DS_C1_H14_KPI_MEASURES_EU_{{ env_var('DBT_REGION') }} TO ROLE _TECH_SDDS_{{ env_var('DBT_REGION') }}_OWN_ROLE;
        GRANT OWNERSHIP ON FUTURE SEQUENCES IN SCHEMA BTDP_DS_C1_H14_KPI_MEASURES_EU_{{ env_var('DBT_REGION') }} TO ROLE _TECH_SDDS_{{ env_var('DBT_REGION') }}_OWN_ROLE;
        GRANT OWNERSHIP ON FUTURE TASKS IN SCHEMA BTDP_DS_C1_H14_KPI_MEASURES_EU_{{ env_var('DBT_REGION') }} TO ROLE _TECH_SDDS_{{ env_var('DBT_REGION') }}_OWN_ROLE;
        --------------------------------------------------------------------------------------------------
        
        --------------------Create Schema---------------------
        CREATE SCHEMA IF NOT EXISTS BTDP_DS_C1_H14_KPI_MEASURES_EU_{{ env_var('DBT_REGION') }}_PRIVATE WITH MANAGED ACCESS;
        --------------------Grant Usage on Schema---------------------
        GRANT USAGE ON SCHEMA BTDP_DS_C1_H14_KPI_MEASURES_EU_{{ env_var('DBT_REGION') }}_PRIVATE TO ROLE _TECH_SDDS_{{ env_var('DBT_REGION') }}_RO_ROLE;
        GRANT ALL PRIVILEGES ON SCHEMA BTDP_DS_C1_H14_KPI_MEASURES_EU_{{ env_var('DBT_REGION') }}_PRIVATE TO ROLE _TECH_SDDS_{{ env_var('DBT_REGION') }}_OWN_ROLE;
        -----------Grants for current Object---------
        GRANT SELECT ON ALL TABLES IN SCHEMA BTDP_DS_C1_H14_KPI_MEASURES_EU_{{ env_var('DBT_REGION') }}_PRIVATE TO ROLE _TECH_SDDS_{{ env_var('DBT_REGION') }}_RO_ROLE;
        GRANT SELECT ON ALL VIEWS IN SCHEMA BTDP_DS_C1_H14_KPI_MEASURES_EU_{{ env_var('DBT_REGION') }}_PRIVATE TO ROLE _TECH_SDDS_{{ env_var('DBT_REGION') }}_RO_ROLE;
        GRANT USAGE, READ ON ALL STAGES IN SCHEMA BTDP_DS_C1_H14_KPI_MEASURES_EU_{{ env_var('DBT_REGION') }}_PRIVATE TO ROLE _TECH_SDDS_{{ env_var('DBT_REGION') }}_RO_ROLE;
        GRANT USAGE ON ALL FILE FORMATS IN SCHEMA BTDP_DS_C1_H14_KPI_MEASURES_EU_{{ env_var('DBT_REGION') }}_PRIVATE TO ROLE _TECH_SDDS_{{ env_var('DBT_REGION') }}_RO_ROLE;
        GRANT SELECT ON ALL STREAMS IN SCHEMA BTDP_DS_C1_H14_KPI_MEASURES_EU_{{ env_var('DBT_REGION') }}_PRIVATE TO ROLE _TECH_SDDS_{{ env_var('DBT_REGION') }}_RO_ROLE;
        GRANT USAGE ON ALL FUNCTIONS IN SCHEMA BTDP_DS_C1_H14_KPI_MEASURES_EU_{{ env_var('DBT_REGION') }}_PRIVATE TO ROLE _TECH_SDDS_{{ env_var('DBT_REGION') }}_RO_ROLE;
        -----------Grants for Future Object---------
        GRANT SELECT ON FUTURE TABLES IN SCHEMA BTDP_DS_C1_H14_KPI_MEASURES_EU_{{ env_var('DBT_REGION') }}_PRIVATE TO ROLE _TECH_SDDS_{{ env_var('DBT_REGION') }}_RO_ROLE;
        GRANT SELECT ON FUTURE VIEWS IN SCHEMA BTDP_DS_C1_H14_KPI_MEASURES_EU_{{ env_var('DBT_REGION') }}_PRIVATE TO ROLE _TECH_SDDS_{{ env_var('DBT_REGION') }}_RO_ROLE;
        GRANT USAGE, READ ON FUTURE STAGES IN SCHEMA BTDP_DS_C1_H14_KPI_MEASURES_EU_{{ env_var('DBT_REGION') }}_PRIVATE TO ROLE _TECH_SDDS_{{ env_var('DBT_REGION') }}_RO_ROLE;
        GRANT USAGE ON FUTURE FILE FORMATS IN SCHEMA BTDP_DS_C1_H14_KPI_MEASURES_EU_{{ env_var('DBT_REGION') }}_PRIVATE TO ROLE _TECH_SDDS_{{ env_var('DBT_REGION') }}_RO_ROLE;
        GRANT SELECT ON FUTURE STREAMS IN SCHEMA BTDP_DS_C1_H14_KPI_MEASURES_EU_{{ env_var('DBT_REGION') }}_PRIVATE TO ROLE _TECH_SDDS_{{ env_var('DBT_REGION') }}_RO_ROLE;
        GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA BTDP_DS_C1_H14_KPI_MEASURES_EU_{{ env_var('DBT_REGION') }}_PRIVATE TO ROLE _TECH_SDDS_{{ env_var('DBT_REGION') }}_RO_ROLE;
        GRANT USAGE ON FUTURE FUNCTIONS IN SCHEMA BTDP_DS_C1_H14_KPI_MEASURES_EU_{{ env_var('DBT_REGION') }}_PRIVATE TO ROLE _TECH_SDDS_{{ env_var('DBT_REGION') }}_RO_ROLE;
        -----------Grant Privileges to Technical Ownership roles---------
        GRANT OWNERSHIP ON ALL TABLES IN SCHEMA BTDP_DS_C1_H14_KPI_MEASURES_EU_{{ env_var('DBT_REGION') }}_PRIVATE TO ROLE _TECH_SDDS_{{ env_var('DBT_REGION') }}_OWN_ROLE;
        GRANT OWNERSHIP ON ALL VIEWS IN SCHEMA BTDP_DS_C1_H14_KPI_MEASURES_EU_{{ env_var('DBT_REGION') }}_PRIVATE TO ROLE _TECH_SDDS_{{ env_var('DBT_REGION') }}_OWN_ROLE;
        GRANT OWNERSHIP ON ALL STAGES IN SCHEMA BTDP_DS_C1_H14_KPI_MEASURES_EU_{{ env_var('DBT_REGION') }}_PRIVATE TO ROLE _TECH_SDDS_{{ env_var('DBT_REGION') }}_OWN_ROLE;
        GRANT OWNERSHIP ON ALL FILE FORMATS IN SCHEMA BTDP_DS_C1_H14_KPI_MEASURES_EU_{{ env_var('DBT_REGION') }}_PRIVATE TO ROLE _TECH_SDDS_{{ env_var('DBT_REGION') }}_OWN_ROLE;
        GRANT OWNERSHIP ON ALL STREAMS IN SCHEMA BTDP_DS_C1_H14_KPI_MEASURES_EU_{{ env_var('DBT_REGION') }}_PRIVATE TO ROLE _TECH_SDDS_{{ env_var('DBT_REGION') }}_OWN_ROLE;
        GRANT OWNERSHIP ON ALL PROCEDURES IN SCHEMA BTDP_DS_C1_H14_KPI_MEASURES_EU_{{ env_var('DBT_REGION') }}_PRIVATE TO ROLE _TECH_SDDS_{{ env_var('DBT_REGION') }}_OWN_ROLE;
        GRANT OWNERSHIP ON ALL FUNCTIONS IN SCHEMA BTDP_DS_C1_H14_KPI_MEASURES_EU_{{ env_var('DBT_REGION') }}_PRIVATE TO ROLE _TECH_SDDS_{{ env_var('DBT_REGION') }}_OWN_ROLE;
        GRANT OWNERSHIP ON ALL SEQUENCES IN SCHEMA BTDP_DS_C1_H14_KPI_MEASURES_EU_{{ env_var('DBT_REGION') }}_PRIVATE TO ROLE _TECH_SDDS_{{ env_var('DBT_REGION') }}_OWN_ROLE;
        GRANT OWNERSHIP ON ALL TASKS IN SCHEMA BTDP_DS_C1_H14_KPI_MEASURES_EU_{{ env_var('DBT_REGION') }}_PRIVATE TO ROLE _TECH_SDDS_{{ env_var('DBT_REGION') }}_OWN_ROLE;
        -----------Grants For Future Object---------
        GRANT OWNERSHIP ON FUTURE TABLES IN SCHEMA BTDP_DS_C1_H14_KPI_MEASURES_EU_{{ env_var('DBT_REGION') }}_PRIVATE TO ROLE _TECH_SDDS_{{ env_var('DBT_REGION') }}_OWN_ROLE;
        GRANT OWNERSHIP ON FUTURE VIEWS IN SCHEMA BTDP_DS_C1_H14_KPI_MEASURES_EU_{{ env_var('DBT_REGION') }}_PRIVATE TO ROLE _TECH_SDDS_{{ env_var('DBT_REGION') }}_OWN_ROLE;
        GRANT OWNERSHIP ON FUTURE STAGES IN SCHEMA BTDP_DS_C1_H14_KPI_MEASURES_EU_{{ env_var('DBT_REGION') }}_PRIVATE TO ROLE _TECH_SDDS_{{ env_var('DBT_REGION') }}_OWN_ROLE;
        GRANT OWNERSHIP ON FUTURE FILE FORMATS IN SCHEMA BTDP_DS_C1_H14_KPI_MEASURES_EU_{{ env_var('DBT_REGION') }}_PRIVATE TO ROLE _TECH_SDDS_{{ env_var('DBT_REGION') }}_OWN_ROLE;
        GRANT OWNERSHIP ON FUTURE STREAMS IN SCHEMA BTDP_DS_C1_H14_KPI_MEASURES_EU_{{ env_var('DBT_REGION') }}_PRIVATE TO ROLE _TECH_SDDS_{{ env_var('DBT_REGION') }}_OWN_ROLE;
        GRANT OWNERSHIP ON FUTURE PROCEDURES IN SCHEMA BTDP_DS_C1_H14_KPI_MEASURES_EU_{{ env_var('DBT_REGION') }}_PRIVATE TO ROLE _TECH_SDDS_{{ env_var('DBT_REGION') }}_OWN_ROLE;
        GRANT OWNERSHIP ON FUTURE FUNCTIONS IN SCHEMA BTDP_DS_C1_H14_KPI_MEASURES_EU_{{ env_var('DBT_REGION') }}_PRIVATE TO ROLE _TECH_SDDS_{{ env_var('DBT_REGION') }}_OWN_ROLE;
        GRANT OWNERSHIP ON FUTURE SEQUENCES IN SCHEMA BTDP_DS_C1_H14_KPI_MEASURES_EU_{{ env_var('DBT_REGION') }}_PRIVATE TO ROLE _TECH_SDDS_{{ env_var('DBT_REGION') }}_OWN_ROLE;
        GRANT OWNERSHIP ON FUTURE TASKS IN SCHEMA BTDP_DS_C1_H14_KPI_MEASURES_EU_{{ env_var('DBT_REGION') }}_PRIVATE TO ROLE _TECH_SDDS_{{ env_var('DBT_REGION') }}_OWN_ROLE;
		
        --------------------Create Schema---------------------
        CREATE SCHEMA IF NOT EXISTS BTDP_DS_C2_H14_KPI_MEASURES_EU_{{ env_var('DBT_REGION') }} WITH MANAGED ACCESS;
        --------------------Grant Usage on Schema---------------------
        GRANT USAGE ON SCHEMA BTDP_DS_C2_H14_KPI_MEASURES_EU_{{ env_var('DBT_REGION') }} TO ROLE _TECH_SDDS_{{ env_var('DBT_REGION') }}_RO_ROLE;
        GRANT ALL PRIVILEGES ON SCHEMA BTDP_DS_C2_H14_KPI_MEASURES_EU_{{ env_var('DBT_REGION') }} TO ROLE _TECH_SDDS_{{ env_var('DBT_REGION') }}_OWN_ROLE;
        -----------Grants for current Object---------
        GRANT SELECT ON ALL TABLES IN SCHEMA BTDP_DS_C2_H14_KPI_MEASURES_EU_{{ env_var('DBT_REGION') }} TO ROLE _TECH_SDDS_{{ env_var('DBT_REGION') }}_RO_ROLE;
        GRANT SELECT ON ALL VIEWS IN SCHEMA BTDP_DS_C2_H14_KPI_MEASURES_EU_{{ env_var('DBT_REGION') }} TO ROLE _TECH_SDDS_{{ env_var('DBT_REGION') }}_RO_ROLE;
        GRANT USAGE, READ ON ALL STAGES IN SCHEMA BTDP_DS_C2_H14_KPI_MEASURES_EU_{{ env_var('DBT_REGION') }} TO ROLE _TECH_SDDS_{{ env_var('DBT_REGION') }}_RO_ROLE;
        GRANT USAGE ON ALL FILE FORMATS IN SCHEMA BTDP_DS_C2_H14_KPI_MEASURES_EU_{{ env_var('DBT_REGION') }} TO ROLE _TECH_SDDS_{{ env_var('DBT_REGION') }}_RO_ROLE;
        GRANT SELECT ON ALL STREAMS IN SCHEMA BTDP_DS_C2_H14_KPI_MEASURES_EU_{{ env_var('DBT_REGION') }} TO ROLE _TECH_SDDS_{{ env_var('DBT_REGION') }}_RO_ROLE;
        GRANT USAGE ON ALL FUNCTIONS IN SCHEMA BTDP_DS_C2_H14_KPI_MEASURES_EU_{{ env_var('DBT_REGION') }} TO ROLE _TECH_SDDS_{{ env_var('DBT_REGION') }}_RO_ROLE;
        -----------Grants for Future Object---------
        GRANT SELECT ON FUTURE TABLES IN SCHEMA BTDP_DS_C2_H14_KPI_MEASURES_EU_{{ env_var('DBT_REGION') }} TO ROLE _TECH_SDDS_{{ env_var('DBT_REGION') }}_RO_ROLE;
        GRANT SELECT ON FUTURE VIEWS IN SCHEMA BTDP_DS_C2_H14_KPI_MEASURES_EU_{{ env_var('DBT_REGION') }} TO ROLE _TECH_SDDS_{{ env_var('DBT_REGION') }}_RO_ROLE;
        GRANT USAGE, READ ON FUTURE STAGES IN SCHEMA BTDP_DS_C2_H14_KPI_MEASURES_EU_{{ env_var('DBT_REGION') }} TO ROLE _TECH_SDDS_{{ env_var('DBT_REGION') }}_RO_ROLE;
        GRANT USAGE ON FUTURE FILE FORMATS IN SCHEMA BTDP_DS_C2_H14_KPI_MEASURES_EU_{{ env_var('DBT_REGION') }} TO ROLE _TECH_SDDS_{{ env_var('DBT_REGION') }}_RO_ROLE;
        GRANT SELECT ON FUTURE STREAMS IN SCHEMA BTDP_DS_C2_H14_KPI_MEASURES_EU_{{ env_var('DBT_REGION') }} TO ROLE _TECH_SDDS_{{ env_var('DBT_REGION') }}_RO_ROLE;
        GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA BTDP_DS_C2_H14_KPI_MEASURES_EU_{{ env_var('DBT_REGION') }} TO ROLE _TECH_SDDS_{{ env_var('DBT_REGION') }}_RO_ROLE;
        GRANT USAGE ON FUTURE FUNCTIONS IN SCHEMA BTDP_DS_C2_H14_KPI_MEASURES_EU_{{ env_var('DBT_REGION') }} TO ROLE _TECH_SDDS_{{ env_var('DBT_REGION') }}_RO_ROLE;
        -----------Grant Privileges to Technical Ownership roles---------
        GRANT OWNERSHIP ON ALL TABLES IN SCHEMA BTDP_DS_C2_H14_KPI_MEASURES_EU_{{ env_var('DBT_REGION') }} TO ROLE _TECH_SDDS_{{ env_var('DBT_REGION') }}_OWN_ROLE;
        GRANT OWNERSHIP ON ALL VIEWS IN SCHEMA BTDP_DS_C2_H14_KPI_MEASURES_EU_{{ env_var('DBT_REGION') }} TO ROLE _TECH_SDDS_{{ env_var('DBT_REGION') }}_OWN_ROLE;
        GRANT OWNERSHIP ON ALL STAGES IN SCHEMA BTDP_DS_C2_H14_KPI_MEASURES_EU_{{ env_var('DBT_REGION') }} TO ROLE _TECH_SDDS_{{ env_var('DBT_REGION') }}_OWN_ROLE;
        GRANT OWNERSHIP ON ALL FILE FORMATS IN SCHEMA BTDP_DS_C2_H14_KPI_MEASURES_EU_{{ env_var('DBT_REGION') }} TO ROLE _TECH_SDDS_{{ env_var('DBT_REGION') }}_OWN_ROLE;
        GRANT OWNERSHIP ON ALL STREAMS IN SCHEMA BTDP_DS_C2_H14_KPI_MEASURES_EU_{{ env_var('DBT_REGION') }} TO ROLE _TECH_SDDS_{{ env_var('DBT_REGION') }}_OWN_ROLE;
        GRANT OWNERSHIP ON ALL PROCEDURES IN SCHEMA BTDP_DS_C2_H14_KPI_MEASURES_EU_{{ env_var('DBT_REGION') }} TO ROLE _TECH_SDDS_{{ env_var('DBT_REGION') }}_OWN_ROLE;
        GRANT OWNERSHIP ON ALL FUNCTIONS IN SCHEMA BTDP_DS_C2_H14_KPI_MEASURES_EU_{{ env_var('DBT_REGION') }} TO ROLE _TECH_SDDS_{{ env_var('DBT_REGION') }}_OWN_ROLE;
        GRANT OWNERSHIP ON ALL SEQUENCES IN SCHEMA BTDP_DS_C2_H14_KPI_MEASURES_EU_{{ env_var('DBT_REGION') }} TO ROLE _TECH_SDDS_{{ env_var('DBT_REGION') }}_OWN_ROLE;
        GRANT OWNERSHIP ON ALL TASKS IN SCHEMA BTDP_DS_C2_H14_KPI_MEASURES_EU_{{ env_var('DBT_REGION') }} TO ROLE _TECH_SDDS_{{ env_var('DBT_REGION') }}_OWN_ROLE;
        -----------Grants For Future Object---------
        GRANT OWNERSHIP ON FUTURE TABLES IN SCHEMA BTDP_DS_C2_H14_KPI_MEASURES_EU_{{ env_var('DBT_REGION') }} TO ROLE _TECH_SDDS_{{ env_var('DBT_REGION') }}_OWN_ROLE;
        GRANT OWNERSHIP ON FUTURE VIEWS IN SCHEMA BTDP_DS_C2_H14_KPI_MEASURES_EU_{{ env_var('DBT_REGION') }} TO ROLE _TECH_SDDS_{{ env_var('DBT_REGION') }}_OWN_ROLE;
        GRANT OWNERSHIP ON FUTURE STAGES IN SCHEMA BTDP_DS_C2_H14_KPI_MEASURES_EU_{{ env_var('DBT_REGION') }} TO ROLE _TECH_SDDS_{{ env_var('DBT_REGION') }}_OWN_ROLE;
        GRANT OWNERSHIP ON FUTURE FILE FORMATS IN SCHEMA BTDP_DS_C2_H14_KPI_MEASURES_EU_{{ env_var('DBT_REGION') }} TO ROLE _TECH_SDDS_{{ env_var('DBT_REGION') }}_OWN_ROLE;
        GRANT OWNERSHIP ON FUTURE STREAMS IN SCHEMA BTDP_DS_C2_H14_KPI_MEASURES_EU_{{ env_var('DBT_REGION') }} TO ROLE _TECH_SDDS_{{ env_var('DBT_REGION') }}_OWN_ROLE;
        GRANT OWNERSHIP ON FUTURE PROCEDURES IN SCHEMA BTDP_DS_C2_H14_KPI_MEASURES_EU_{{ env_var('DBT_REGION') }} TO ROLE _TECH_SDDS_{{ env_var('DBT_REGION') }}_OWN_ROLE;
        GRANT OWNERSHIP ON FUTURE FUNCTIONS IN SCHEMA BTDP_DS_C2_H14_KPI_MEASURES_EU_{{ env_var('DBT_REGION') }} TO ROLE _TECH_SDDS_{{ env_var('DBT_REGION') }}_OWN_ROLE;
        GRANT OWNERSHIP ON FUTURE SEQUENCES IN SCHEMA BTDP_DS_C2_H14_KPI_MEASURES_EU_{{ env_var('DBT_REGION') }} TO ROLE _TECH_SDDS_{{ env_var('DBT_REGION') }}_OWN_ROLE;
        GRANT OWNERSHIP ON FUTURE TASKS IN SCHEMA BTDP_DS_C2_H14_KPI_MEASURES_EU_{{ env_var('DBT_REGION') }} TO ROLE _TECH_SDDS_{{ env_var('DBT_REGION') }}_OWN_ROLE;
        --------------------------------------------------------------------------------------------------
        
        --------------------Create Schema---------------------
        CREATE SCHEMA IF NOT EXISTS BTDP_DS_C2_H14_KPI_MEASURES_EU_{{ env_var('DBT_REGION') }}_PRIVATE WITH MANAGED ACCESS;
        --------------------Grant Usage on Schema---------------------
        GRANT USAGE ON SCHEMA BTDP_DS_C2_H14_KPI_MEASURES_EU_{{ env_var('DBT_REGION') }}_PRIVATE TO ROLE _TECH_SDDS_{{ env_var('DBT_REGION') }}_RO_ROLE;
        GRANT ALL PRIVILEGES ON SCHEMA BTDP_DS_C2_H14_KPI_MEASURES_EU_{{ env_var('DBT_REGION') }}_PRIVATE TO ROLE _TECH_SDDS_{{ env_var('DBT_REGION') }}_OWN_ROLE;
        -----------Grants for current Object---------
        GRANT SELECT ON ALL TABLES IN SCHEMA BTDP_DS_C2_H14_KPI_MEASURES_EU_{{ env_var('DBT_REGION') }}_PRIVATE TO ROLE _TECH_SDDS_{{ env_var('DBT_REGION') }}_RO_ROLE;
        GRANT SELECT ON ALL VIEWS IN SCHEMA BTDP_DS_C2_H14_KPI_MEASURES_EU_{{ env_var('DBT_REGION') }}_PRIVATE TO ROLE _TECH_SDDS_{{ env_var('DBT_REGION') }}_RO_ROLE;
        GRANT USAGE, READ ON ALL STAGES IN SCHEMA BTDP_DS_C2_H14_KPI_MEASURES_EU_{{ env_var('DBT_REGION') }}_PRIVATE TO ROLE _TECH_SDDS_{{ env_var('DBT_REGION') }}_RO_ROLE;
        GRANT USAGE ON ALL FILE FORMATS IN SCHEMA BTDP_DS_C2_H14_KPI_MEASURES_EU_{{ env_var('DBT_REGION') }}_PRIVATE TO ROLE _TECH_SDDS_{{ env_var('DBT_REGION') }}_RO_ROLE;
        GRANT SELECT ON ALL STREAMS IN SCHEMA BTDP_DS_C2_H14_KPI_MEASURES_EU_{{ env_var('DBT_REGION') }}_PRIVATE TO ROLE _TECH_SDDS_{{ env_var('DBT_REGION') }}_RO_ROLE;
        GRANT USAGE ON ALL FUNCTIONS IN SCHEMA BTDP_DS_C2_H14_KPI_MEASURES_EU_{{ env_var('DBT_REGION') }}_PRIVATE TO ROLE _TECH_SDDS_{{ env_var('DBT_REGION') }}_RO_ROLE;
        -----------Grants for Future Object---------
        GRANT SELECT ON FUTURE TABLES IN SCHEMA BTDP_DS_C2_H14_KPI_MEASURES_EU_{{ env_var('DBT_REGION') }}_PRIVATE TO ROLE _TECH_SDDS_{{ env_var('DBT_REGION') }}_RO_ROLE;
        GRANT SELECT ON FUTURE VIEWS IN SCHEMA BTDP_DS_C2_H14_KPI_MEASURES_EU_{{ env_var('DBT_REGION') }}_PRIVATE TO ROLE _TECH_SDDS_{{ env_var('DBT_REGION') }}_RO_ROLE;
        GRANT USAGE, READ ON FUTURE STAGES IN SCHEMA BTDP_DS_C2_H14_KPI_MEASURES_EU_{{ env_var('DBT_REGION') }}_PRIVATE TO ROLE _TECH_SDDS_{{ env_var('DBT_REGION') }}_RO_ROLE;
        GRANT USAGE ON FUTURE FILE FORMATS IN SCHEMA BTDP_DS_C2_H14_KPI_MEASURES_EU_{{ env_var('DBT_REGION') }}_PRIVATE TO ROLE _TECH_SDDS_{{ env_var('DBT_REGION') }}_RO_ROLE;
        GRANT SELECT ON FUTURE STREAMS IN SCHEMA BTDP_DS_C2_H14_KPI_MEASURES_EU_{{ env_var('DBT_REGION') }}_PRIVATE TO ROLE _TECH_SDDS_{{ env_var('DBT_REGION') }}_RO_ROLE;
        GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA BTDP_DS_C2_H14_KPI_MEASURES_EU_{{ env_var('DBT_REGION') }}_PRIVATE TO ROLE _TECH_SDDS_{{ env_var('DBT_REGION') }}_RO_ROLE;
        GRANT USAGE ON FUTURE FUNCTIONS IN SCHEMA BTDP_DS_C2_H14_KPI_MEASURES_EU_{{ env_var('DBT_REGION') }}_PRIVATE TO ROLE _TECH_SDDS_{{ env_var('DBT_REGION') }}_RO_ROLE;
        -----------Grant Privileges to Technical Ownership roles---------
        GRANT OWNERSHIP ON ALL TABLES IN SCHEMA BTDP_DS_C2_H14_KPI_MEASURES_EU_{{ env_var('DBT_REGION') }}_PRIVATE TO ROLE _TECH_SDDS_{{ env_var('DBT_REGION') }}_OWN_ROLE;
        GRANT OWNERSHIP ON ALL VIEWS IN SCHEMA BTDP_DS_C2_H14_KPI_MEASURES_EU_{{ env_var('DBT_REGION') }}_PRIVATE TO ROLE _TECH_SDDS_{{ env_var('DBT_REGION') }}_OWN_ROLE;
        GRANT OWNERSHIP ON ALL STAGES IN SCHEMA BTDP_DS_C2_H14_KPI_MEASURES_EU_{{ env_var('DBT_REGION') }}_PRIVATE TO ROLE _TECH_SDDS_{{ env_var('DBT_REGION') }}_OWN_ROLE;
        GRANT OWNERSHIP ON ALL FILE FORMATS IN SCHEMA BTDP_DS_C2_H14_KPI_MEASURES_EU_{{ env_var('DBT_REGION') }}_PRIVATE TO ROLE _TECH_SDDS_{{ env_var('DBT_REGION') }}_OWN_ROLE;
        GRANT OWNERSHIP ON ALL STREAMS IN SCHEMA BTDP_DS_C2_H14_KPI_MEASURES_EU_{{ env_var('DBT_REGION') }}_PRIVATE TO ROLE _TECH_SDDS_{{ env_var('DBT_REGION') }}_OWN_ROLE;
        GRANT OWNERSHIP ON ALL PROCEDURES IN SCHEMA BTDP_DS_C2_H14_KPI_MEASURES_EU_{{ env_var('DBT_REGION') }}_PRIVATE TO ROLE _TECH_SDDS_{{ env_var('DBT_REGION') }}_OWN_ROLE;
        GRANT OWNERSHIP ON ALL FUNCTIONS IN SCHEMA BTDP_DS_C2_H14_KPI_MEASURES_EU_{{ env_var('DBT_REGION') }}_PRIVATE TO ROLE _TECH_SDDS_{{ env_var('DBT_REGION') }}_OWN_ROLE;
        GRANT OWNERSHIP ON ALL SEQUENCES IN SCHEMA BTDP_DS_C2_H14_KPI_MEASURES_EU_{{ env_var('DBT_REGION') }}_PRIVATE TO ROLE _TECH_SDDS_{{ env_var('DBT_REGION') }}_OWN_ROLE;
        GRANT OWNERSHIP ON ALL TASKS IN SCHEMA BTDP_DS_C2_H14_KPI_MEASURES_EU_{{ env_var('DBT_REGION') }}_PRIVATE TO ROLE _TECH_SDDS_{{ env_var('DBT_REGION') }}_OWN_ROLE;
        -----------Grants For Future Object---------
        GRANT OWNERSHIP ON FUTURE TABLES IN SCHEMA BTDP_DS_C2_H14_KPI_MEASURES_EU_{{ env_var('DBT_REGION') }}_PRIVATE TO ROLE _TECH_SDDS_{{ env_var('DBT_REGION') }}_OWN_ROLE;
        GRANT OWNERSHIP ON FUTURE VIEWS IN SCHEMA BTDP_DS_C2_H14_KPI_MEASURES_EU_{{ env_var('DBT_REGION') }}_PRIVATE TO ROLE _TECH_SDDS_{{ env_var('DBT_REGION') }}_OWN_ROLE;
        GRANT OWNERSHIP ON FUTURE STAGES IN SCHEMA BTDP_DS_C2_H14_KPI_MEASURES_EU_{{ env_var('DBT_REGION') }}_PRIVATE TO ROLE _TECH_SDDS_{{ env_var('DBT_REGION') }}_OWN_ROLE;
        GRANT OWNERSHIP ON FUTURE FILE FORMATS IN SCHEMA BTDP_DS_C2_H14_KPI_MEASURES_EU_{{ env_var('DBT_REGION') }}_PRIVATE TO ROLE _TECH_SDDS_{{ env_var('DBT_REGION') }}_OWN_ROLE;
        GRANT OWNERSHIP ON FUTURE STREAMS IN SCHEMA BTDP_DS_C2_H14_KPI_MEASURES_EU_{{ env_var('DBT_REGION') }}_PRIVATE TO ROLE _TECH_SDDS_{{ env_var('DBT_REGION') }}_OWN_ROLE;
        GRANT OWNERSHIP ON FUTURE PROCEDURES IN SCHEMA BTDP_DS_C2_H14_KPI_MEASURES_EU_{{ env_var('DBT_REGION') }}_PRIVATE TO ROLE _TECH_SDDS_{{ env_var('DBT_REGION') }}_OWN_ROLE;
        GRANT OWNERSHIP ON FUTURE FUNCTIONS IN SCHEMA BTDP_DS_C2_H14_KPI_MEASURES_EU_{{ env_var('DBT_REGION') }}_PRIVATE TO ROLE _TECH_SDDS_{{ env_var('DBT_REGION') }}_OWN_ROLE;
        GRANT OWNERSHIP ON FUTURE SEQUENCES IN SCHEMA BTDP_DS_C2_H14_KPI_MEASURES_EU_{{ env_var('DBT_REGION') }}_PRIVATE TO ROLE _TECH_SDDS_{{ env_var('DBT_REGION') }}_OWN_ROLE;
        GRANT OWNERSHIP ON FUTURE TASKS IN SCHEMA BTDP_DS_C2_H14_KPI_MEASURES_EU_{{ env_var('DBT_REGION') }}_PRIVATE TO ROLE _TECH_SDDS_{{ env_var('DBT_REGION') }}_OWN_ROLE;

    {% endset %}

    {% do run_query(query) %}

{% endmacro %}