{% macro sp_csrd_recalculate_data(MONTH_REF, COUNTRY_CODE) %}
    {% set query %}

CREATE OR REPLACE PROCEDURE HRDP_SDDS_{{ env_var('DBT_REGION') }}_DB.BTDP_DS_C2_H16_CSRD_EU_{{ env_var('DBT_REGION') }}_PRIVATE.SP_CSRD_RECALCULATE_DATA("MONTH_REF" NUMBER(38,0), "COUNTRY_CODE" VARCHAR(16777216))
RETURNS VARCHAR(16777216)
LANGUAGE SQL
EXECUTE AS OWNER
AS 'BEGIN

DELETE FROM HRDP_SDDS_{{ env_var('DBT_REGION') }}_DB.BTDP_DS_C2_H16_CSRD_EU_{{ env_var('DBT_REGION') }}_PRIVATE.CSRD_HEADCOUNT_DETAILS_HISTO
WHERE COUNTRY_CODE = :COUNTRY_CODE AND CSRD_HDH_CALCULATION_DATE = :MONTH_REF;

INSERT INTO HRDP_SDDS_{{ env_var('DBT_REGION') }}_DB.BTDP_DS_C2_H16_CSRD_EU_{{ env_var('DBT_REGION') }}_PRIVATE.CSRD_HEADCOUNT_DETAILS_HISTO
(
CSRD_HDH_ID,
CSRD_HDH_CALCULATION_DATE,
CSRD_HD_ID,
CSRD_HD_START_DATE,
CSRD_HD_END_DATE,
PERSONAL_ID,
USER_ID,
LEGAL_GENDER_CODE,
LEGAL_GENDER_NAME_EN,
EMPLOYEE_STATUS_CODE,
EMPLOYEE_STATUS_NAME_EN,
LOCAL_CONTRACT_TYPE_CODE,
LOCAL_CONTRACT_TYPE_NAME_EN,
EMPLOYEE_GROUP_CODE,
EMPLOYEE_GROUP_NAME_EN,
COST_CENTER_CODE,
COST_CENTER_NAME_EN,
BUSINESS_UNIT_CODE,
BUSINESS_UNIT_NAME_EN,
COMPANY_CODE,
COMPANY_NAME_EN,
COUNTRY_CODE,
COUNTRY_NAME_EN,
GEOGRAPHIC_ZONE_CODE,
GEOGRAPHIC_ZONE_NAME_EN,
DISABILITY_STATUS_CODE,
DISABILITY_STATUS_NAME_EN,
KEY_POSITION_TYPE_CODE,
KEY_POSITION_TYPE_NAME_EN,
IS_CSRD_HEADCOUNT_FLAG,
TERMINATION_DATE,
FTE,
EMPLOYEE_SUBGROUP_CODE,
EMPLOYEE_SUBGROUP_NAME_EN,
BUSINESS_UNIT_TYPE_CODE,
BUSINESS_UNIT_TYPE_NAME_EN
)
SELECT 
    hash(csrd_hd_id, :MONTH_REF) as csrd_hdh_id,
    :MONTH_REF as csrd_hdh_calculation_date,
CSRD_HD_ID,
CSRD_HD_START_DATE,
CSRD_HD_END_DATE,
PERSONAL_ID,
USER_ID,
LEGAL_GENDER_CODE,
LEGAL_GENDER_NAME_EN,
EMPLOYEE_STATUS_CODE,
EMPLOYEE_STATUS_NAME_EN,
LOCAL_CONTRACT_TYPE_CODE,
LOCAL_CONTRACT_TYPE_NAME_EN,
EMPLOYEE_GROUP_CODE,
EMPLOYEE_GROUP_NAME_EN,
COST_CENTER_CODE,
COST_CENTER_NAME_EN,
BUSINESS_UNIT_CODE,
BUSINESS_UNIT_NAME_EN,
COMPANY_CODE,
COMPANY_NAME_EN,
COUNTRY_CODE,
COUNTRY_NAME_EN,
GEOGRAPHIC_ZONE_CODE,
GEOGRAPHIC_ZONE_NAME_EN,
DISABILITY_STATUS_CODE,
DISABILITY_STATUS_NAME_EN,
KEY_POSITION_TYPE_CODE,
KEY_POSITION_TYPE_NAME_EN,
IS_CSRD_HEADCOUNT_FLAG,
TERMINATION_DATE,
FTE,
EMPLOYEE_SUBGROUP_CODE,
EMPLOYEE_SUBGROUP_NAME_EN,
BUSINESS_UNIT_TYPE_CODE,
BUSINESS_UNIT_TYPE_NAME_EN
    FROM HRDP_SDDS_{{ env_var('DBT_REGION') }}_DB.BTDP_DS_C2_H16_CSRD_EU_{{ env_var('DBT_REGION') }}_PRIVATE.CSRD_HEADCOUNT_DETAILS 
WHERE COUNTRY_CODE = :COUNTRY_CODE;
RETURN concat (''The country : '', :COUNTRY_CODE ,'' has been reintegrated into the historical table for the month : '' , :MONTH_REF::string);
END';

 
    {% endset %}

    {% do run_query(query) %}

{% endmacro %}
