{{ config(materialized="table", transient=false) }}

SELECT DISTINCT REEU_SUBJECT_DOMAIN_REEU ,
REEU_ACCESS_EMPLOYEE_ID_REEM , 
REEU_ACCESS_EMPLOYEE_UPN_DDEP ,
IFF (REEU_EMPLOYEE_ID_DDEP='ALL', 'ALL',DDEP_BU_CODE_DDEP) AS REEU_BU_CODE_DDEP ,
IFF (REEU_EMPLOYEE_ID_DDEP='ALL', 'ALL',DDEP_PROFESSIONAL_FIELD_CODE_DDEP) AS REEU_PROFESSIONAL_FIELD_CODE_DDEP
FROM {{ source("QCK_RLS_SOURCE_TABLES", "REL_EMPLOYEE_USER") }} t1  LEFT OUTER JOIN {{ source("QCK_RLS_SOURCE_TABLES", "DIM_EMPLOYEE_PROFILE") }}  t2 
     ON t1.REEU_EMPLOYEE_ID_DDEP = t2.DDEP_EMPLOYEE_ID_DDEP