USE ROLE SYSADMIN;
CREATE DATABASE IF NOT EXISTS RLS_DEMO_DB;
USE DATABASE RLS_DEMO_DB;
CREATE SCHEMA IF NOT EXISTS COMPENSATION WITH MANAGED ACCESS;
CREATE SCHEMA IF NOT EXISTS SECURITY WITH MANAGED ACCESS;

--create entitlement table
CREATE OR REPLACE TRANSIENT TABLE SECURITY.ORG_RLS
(
     COST_CENTER VARCHAR
    ,ENTITY VARCHAR
    ,SCOPE VARCHAR
    ,USER_NAME VARCHAR
);

--populate entitlement table
INSERT OVERWRITE INTO SECURITY.ORG_RLS
(
     COST_CENTER
    ,ENTITY
    ,SCOPE
    ,USER_NAME
)
VALUES
 ('CC01','ENT01','EUROPE','OSUNI')
,('CC02','ENT02','AMERICAS','TEST_USER');

--create test content table
CREATE OR REPLACE TRANSIENT TABLE COMPENSATION.EMPLOYEE_SALARY
(
     EMPLOYEE_NAME VARCHAR
    ,COST_CENTER VARCHAR
    ,ENTITY VARCHAR
    ,SCOPE VARCHAR
    ,CURRENT_SALARY DECIMAL(10,2)
);

--populate test content table
INSERT INTO COMPENSATION.EMPLOYEE_SALARY
(
     EMPLOYEE_NAME 
    ,COST_CENTER
    ,ENTITY
    ,SCOPE
    ,CURRENT_SALARY
)
VALUES 
 ('OLLE','CC01','ENT01','EUROPE',100.00)
,('OLIVER','CC02','ENT02','AMERICAS',100.00);


--define row access policy based current_user
CREATE OR REPLACE ROW ACCESS POLICY SECURITY.CC_ENT_SCOPE_RAP AS
(
     P_COST_CENTER VARCHAR
    ,P_ENTITY VARCHAR
    ,P_SCOPE VARCHAR
) 
RETURNS BOOLEAN ->
EXISTS
(
    SELECT 1
    FROM SECURITY.ORG_RLS
    WHERE USER_NAME = CURRENT_USER()
    AND COST_CENTER = P_COST_CENTER
    AND ENTITY      = P_ENTITY
    AND SCOPE       = P_SCOPE
);

--enable/disable RAP on the table
ALTER TABLE COMPENSATION.EMPLOYEE_SALARY ADD  ROW ACCESS POLICY SECURITY.CC_ENT_SCOPE_RAP ON (COST_CENTER, ENTITY, SCOPE);
ALTER TABLE COMPENSATION.EMPLOYEE_SALARY DROP ROW ACCESS POLICY SECURITY.CC_ENT_SCOPE_RAP;

--test RAP
SELECT CURRENT_USER(); --OSUNI
SELECT * FROM COMPENSATION.EMPLOYEE_SALARY; --data is filtered according to RAP
EXECUTE USING POLICY_CONTEXT (CURRENT_USER => 'TEST_USER') AS SELECT * FROM COMPENSATION.EMPLOYEE_SALARY; --data is filtered according to RAP



