Use database comm_us_etl_dev_db; 
use role comm_domain_admin;
 select COUNT(*) from INFORMATION_SCHEMA.TABLES where TABLE_SCHEMA = 'CDW_WORK' and TABLE_NAME like 'I1242_EXT_ADAM_PRES_ER%';
   SELECT COUNT(0) FROM(SELECT DISTINCT src_prod_id,COUNT(0) FROM c_l_prod_price WHERE source_system = 'SHS' AND origin_src_system = 'SHS' GROUP BY src_prod_id HAVING COUNT(0) > 1);
   SELECT COUNT(0) FROM(SELECT DISTINCT pkey_src_id,prod_desc,prod_nm FROM c_l_prod_master WHERE source_system = 'SHS' AND origin_src_system = 'SHS' MINUS SELECT DISTINCT pkey_src_object,prod_desc,prod_nm FROM c_prod_master_xref WHERE rowid_system = 'SHS');
   select date || '-TOTAL_RECORDS_LOADED' GROUPBY,count(*) from(select distinct a.pfz_cust_id,TRIM(COALESCE(b.fname,'')) as hcp_fname,TRIM(COALESCE(b.midl_nm,'')) as hcp_mname,TRIM(COALESCE(b.lname,'')) as hcp_lname,b.titl_cd as hcp_cdtl,b.ims_cust_id,d.st_cd,d.st_lic_num,d.sln_exprn_dt,d.sln_authn_stat_cd from(select distinct x.pfz_cust_id from CDW_US_PROCESSING_VW.dim_cust_hcp x inner join CDW_US_PROCESSING_VW.dim_cust_xref y on x.pfz_cust_id = y.pfz_cust_id and x.pres_prof_type_id = '00' and y.src_sys in('VVA','IMS') and x.cur_ind = 'Y' and x.del_ind = 'N' and y.cur_ind = 'Y' and y.del_ind = 'N') a inner join CDW_US_PROCESSING_VW.dim_cust_hcp b on a.pfz_cust_id = b.pfz_cust_Id inner join CDW_US_PROCESSING_VW.dim_cust_sln d on(b.pfz_cust_Id = d.pfz_cust_id and d.cur_ind = 'Y' and d.del_ind = 'N')) t GROUP BY 1 ORDER BY 1 DESC;
   select count(*) from pm_snd_gen_stg where origin_src_system = 'MLG' and(src_prod_id is null or prod_nm is null or product_brand is null);
   select count(*) from(Select count(*) from c_l_prod_master where origin_src_system = 'MLG' minus select count(*) from pm_snd_gen_stg where origin_src_system = 'MLG');
   select count(*) from(Select pkey_src_id || SRC_PROD_ID || PROD_NM || PROD_DESC || MKT_ENTRY_DT || VALID_FG || SOURCE_SYSTEM from c_l_prod_master where origin_src_system = 'MLG' minus Select pkey_src_id || SRC_PROD_ID || PROD_NM || PROD_DESC || START_DATE || VALID_FG || SRC_SYSTEM from pm_snd_gen_stg where origin_src_system = 'MLG');
   select count(*) from(select PARENT_PROD_ID || HIERARCHY_ID || RELN_TYPE_ID from c_l_prod_hier where PARENT_SOURCE_SYSTEM = 'MLG' minus select 'MLG_' || SRC_PROD_ID || 'SEC_SALES' || 'SEC_SALES' from pm_snd_gen_stg where origin_src_system = 'MLG');
   select count(*) from(select count(*) from c_l_prod_hier where PARENT_SOURCE_SYSTEM = 'MLG' and del_ind = 'N' minus select count(*) from pm_snd_gen_stg where product_brand in(select prod_nm from c_prod_master_xref where origin_src_system = 'PFZ_SLS_R' and prod_level = 'RPTGRP' and del_ind = 'N' and prod_type_cd = 'P' union select prod_nm from c_prod_master_xref where origin_src_system = 'PFZ_SLS_R' and prod_level = 'RPTGRP' and del_ind = 'N') and origin_src_system = 'MLG' and Valid_fg = 'Y');
   SELECT COUNT(*) FROM CDW_US_PROCESSING_VW.ADS_DIM_PYR_CHNL_W WHERE CUR_IND = 1 AND DEL_IND = 0;
   select count(*) from CDW_US_PROCESSING_VW.ads_dim_pyr_w where pyr_sk < 0 and pyr_sk > -101;
   select count(*) from(select count(*) cnt1 from CDW_US_PROCESSING_VW.ads_rel_plan_pyr_w where pyr_sk = -100 minus select count(*) cnt2 from CDW_US_PROCESSING_VW.ads_rel_plan_pyr_w where pyr_sk <> -100 and pyr_sk < 0) a;
   SELECT COUNT(*) FROM(SELECT MCO_SUB_TYPE_1_CD,count(distinct pfz_plan_id) PFZ_PLAN_CNT FROM CDW_US_PROCESSING_VW.dim_cust_plan_vew group by MCO_SUB_TYPE_1_CD minus select b.pyr_nm,count(distinct a.PFZ_PLAN_ID) PFZ_PLAN_CNT from CDW_US_PROCESSING_VW.ads_rel_plan_pyr_w a,CDW_US_PROCESSING_VW.ads_dim_pyr_w b where a.pyr_sk < 0 and a.pyr_sk <> -100 and a.pyr_sk = b.pyr_sk and b.cur_ind = 1 and a.vald_ind = 1 group by b.pyr_nm) A;
   select COUNT(*) from INFORMATION_SCHEMA.TABLES where TABLE_SCHEMA = 'CDW_WORK' and TABLE_NAME like 'I1382_DIM_HCOS_CLNCL_CD_ER%';
   select COUNT(*) from INFORMATION_SCHEMA.TABLES where TABLE_SCHEMA = 'CDW_WORK' and TABLE_NAME like 'I1382__FCT_HCOS_NTNL_CLNCL_ER%';
   select COUNT(*) from INFORMATION_SCHEMA.TABLES where TABLE_SCHEMA = 'CDW_WORK' and TABLE_NAME like 'I1382_HCOS_CLNCL_FCT_ST_ER%';
   select COUNT(*) from INFORMATION_SCHEMA.TABLES where TABLE_SCHEMA = 'CDW_WORK' and TABLE_NAME like 'I1382_HCOS_CLNCL_FCT_TMP_ER%';
   select COUNT(*) from INFORMATION_SCHEMA.TABLES where TABLE_SCHEMA = 'CDW_WORK' and TABLE_NAME like 'I1382_HCOS_CLNCL_REL_FCT_ER%';
   select count(*) from(select IMS_ORG_ID,CUST_XREF_SK,CODE_ID,DATA_YEAR,INPAT_VOL,OUTPAT_VOL,TTL_VOL,DECILE,AVG_LOS,AVG_COS,CODE_ORDER,GPO_VIEW,USE_FOR_AGG from CDW_US_PROCESSING_VW.FCT_HCOS_CLNCL_TMP minus select IMS_ORG_ID,CUST_XREF_SK,CODE_ID,DATA_YEAR,INPAT_VOL,OUTPAT_VOL,TTL_VOL,DECILE,AVG_LOS,AVG_COS,CODE_ORDER,GPO_VIEW,USE_FOR_AGG from CDW_US_PROCESSING_VW.FCT_HCOS_CLNCL where CUR_IND = Y) A;
   select count(*) from(SELECT CODE_ID,DATA_YEAR,INPAT_VOL,OUTPAT_VOL,TTL_VOL,AVG_LOS,AVG_COS,TREND,CODE_ORDER FROM CDW_US_STG.FCT_HCOS_NTNL_CLNCL_TMP MINUS SELECT CODE_ID,DATA_YEAR,INPAT_VOL,OUTPAT_VOL,TTL_VOL,AVG_LOS,AVG_COS,TREND,CODE_ORDER FROM CDW_US_PROCESSING_VW.FCT_HCOS_NTNL_CLNCL WHERE CUR_IND = 'Y') A;
   select count(*) from(SELECT CODE_ID,DATA_YEAR,STATE,INPAT_VOL,OUTPAT_VOL,TTL_VOL,AVG_LOS,AVG_COS,CODE_ORDER FROM CDW_US_STG.FCT_HCOS_ST_CLNCL_TMP MINUS SELECT CODE_ID,DATA_YEAR,STATE,INPAT_VOL, OUTPAT_VOL,TTL_VOL,AVG_LOS,AVG_COS,CODE_ORDER FROM CDW_US_PROCESSING_VW.FCT_HCOS_ST_CLNCL WHERE CUR_IND = 'Y') A;
   SELECT COUNT(0) FROM(SELECT pkey_src_id,prod_desc,prod_nm,COUNT(0) FROM c_l_prod_master WHERE source_system = 'SHS' AND del_ind = 'N' GROUP BY pkey_src_id,prod_desc,prod_nm HAVING COUNT(0) > 1);
   select count(*) from(select * from(select pkey_src_id,origin_src_system from c_s_ims_prod_master_prl where del_ind = 'N' union select pkey_src_id,origin_src_system from c_s_fdb_prod_master_prl where del_ind = 'N' union select pkey_src_id,origin_src_system from c_s_sec_prod_master_prl where del_ind = 'N') minus select pkey_src_object,origin_src_system from c_prod_master_xref where del_ind = 'N' and rowid_system in(select rowid_system from c_repos_system where system_name in('IMS','FDB','SEC')));
   select count(*) from(select pkey_src_object,origin_src_system from c_brand_hier_xref where del_ind = 'N' and rowid_system in(select rowid_system from c_repos_system where system_name in('IMS','FDB','SEC')) minus select * from(select pkey_src_id,origin_src_system from c_s_ims_brand_hier_prl where del_ind = 'N' union select pkey_src_id,origin_src_system from c_s_sec_brand_hier_prl where del_ind = 'N'));
   select count(*) from(select pkey_src_object,origin_src_system from c_prod_price_xref where del_ind = 'N' and rowid_system in(select rowid_system from c_repos_system where system_name in('IMS','FDB','SEC')) minus select * from(select pkey_src_id,origin_src_system from c_s_ims_prod_price_prl where del_ind = 'N' union select pkey_src_id,origin_src_system from c_s_fdb_prod_price_prl where del_ind = 'N' union select pkey_src_id,origin_src_system from c_s_sec_prod_price_prl where del_ind = 'N'));
   select count(*) from(select pkey_src_object,origin_src_system from c_mkt_std_hier_xref where del_ind = 'N' and rowid_system in(select rowid_system from c_repos_system where system_name in('IMS','FDB','SEC')) minus select pkey_src_id,origin_src_system from c_s_pfz_mkt_std_hier_prl where del_ind = 'N');
   select count(*) from(select * from(select pkey_src_object,origin_src_system from c_s_ims_prod_master where del_ind = 'N' union select pkey_src_object,origin_src_system from c_s_fdb_prod_master where del_ind = 'N' union select pkey_src_object,origin_src_system from c_s_sec_prod_master where del_ind = 'N') minus select pkey_src_object,origin_src_system from c_prod_master_xref where del_ind = 'N' and rowid_system in(select rowid_system from c_repos_system where system_name in('IMS','FDB','SEC')));
   select count(*) from(select * from(select pkey_src_object,origin_src_system from c_s_ims_brand_hier where del_ind = 'N' union select pkey_src_object,origin_src_system from c_s_sec_brand_hier where del_ind = 'N') minus select pkey_src_object,origin_src_system from c_brand_hier_xref where del_ind = 'N' and rowid_system in(select rowid_system from c_repos_system where system_name in('IMS','FDB','SEC')));
   select count(*) from(select * from(select pkey_src_object,origin_src_system from c_s_ims_prod_price where del_ind = 'N' union select pkey_src_object,origin_src_system from c_s_fdb_prod_price where del_ind = 'N') minus select pkey_src_object,origin_src_system from c_prod_price_xref where del_ind = 'N' and rowid_system in(select rowid_system from c_repos_system where system_name in('IMS','FDB','SEC')));
   select count(*) from(select pkey_src_object,origin_src_system from c_s_pfz_mkt_std_hier where del_ind = 'N' minus select pkey_src_object,origin_src_system from c_mkt_std_hier_xref where del_ind = 'N' and rowid_system in(select rowid_system from c_repos_system where system_name in('IMS','FDB','SEC')));
   select count(*) from pm_snd_gen_stg where origin_src_system = 'PRM' and(src_prod_id is null or prod_nm is null or product_brand is null);
   select count(*) from(Select count(*) from c_l_prod_master where origin_src_system = 'PRM' and del_ind = 'N' minus select count(*) from pm_snd_gen_stg where origin_src_system = 'PRM');
   select count(*) from(Select pkey_src_id || SRC_PROD_ID || PROD_NM || PROD_DESC || MKT_ENTRY_DT || VALID_FG || SOURCE_SYSTEM from c_l_prod_master where origin_src_system = 'PRM' and del_ind = 'N' minus Select pkey_src_id || SRC_PROD_ID || PROD_NM || PROD_DESC || START_DATE || VALID_FG || SRC_SYSTEM from pm_snd_gen_stg where origin_src_system = 'PRM');
   select count(*) from(select count(*) from c_l_prod_price where origin_src_system = 'PRM' and del_ind = 'N' minus select count(*) from pm_snd_gen_stg where origin_src_system = 'PRM');
   select count(*) from(select PARENT_PROD_ID || HIERARCHY_ID || RELN_TYPE_ID from c_l_prod_hier where PARENT_SOURCE_SYSTEM = 'PRM' and del_ind = 'N' minus select 'PRM_' || SRC_PROD_ID || 'SEC_SALES' || 'SEC_SALES' from pm_snd_gen_stg where origin_src_system = 'PRM');
   select count(*) from(select count(*) from pm_snd_gen_stg where product_brand in(select prod_nm from c_prod_master_xref where origin_src_system = 'PFZ_SLS_R' and prod_level = 'RPTGRP' and del_ind = 'N' and prod_type_cd = 'P' union select prod_nm from c_prod_master_xref where origin_src_system = 'PFZ_SLS_R' and prod_level = 'RPTGRP' and del_ind = 'N') and origin_src_system = 'PRM' minus select count(*) from c_l_prod_hier where creator = 'PRM' and del_ind = 'N');
   select count(*) from(select pkey_src_id || prod_price || price_cd || price_desc from c_l_prod_price where origin_src_system = 'PRM' and del_ind = 'N' minus select src_prod_id || origin_src_system || product_price || 'UC' || 'Unit Cost' from pm_snd_gen_stg where origin_src_system = 'PRM');
   select count(*) from(select count(*) ,crp from pm_ims_corp_lkp group by crp having count(*) > 1);
   select count(*) from pm_ims_corp_lkp where crp is null or crp_name is null;
   select count(*) from(select count(*) ,frm3 from pm_ims_frm3_lkp group by frm3 having count(*) > 1);
   select count(*) from pm_ims_frm3_lkp where frm3 is null or frm_descr is null;
   select count(*) from(select count(*) ,delsys_code from pm_ims_delsys_lkp group by delsys_code having count(*) > 1);
   select count(*) from pm_ims_delsys_lkp where delsys_code is null or delsys_descr is null;
   select count(*) from(select count(*) ,mfr from pm_ims_mfr_lkp group by mfr having count(*) > 1);
   select count(*) from pm_ims_mfr_lkp where mfr is null or mfr_abrev is null or mfr_name is null or crp is null;
   select count(*) from(select count(*) ,tlc_code from pm_ims_tlc_lkp group by tlc_code having count(*) > 1);
   select count(*) from pm_ims_tlc_lkp where tlc_code is null or tlc_descr is null;
   select count(*) from(select count(*) ,usc_code from pm_ims_usc_lkp group by usc_code having count(*) > 1);
   select count(*) from pm_ims_usc_lkp where usc_code is null or usc_descr is null;
   select count(*) from(select count(*) ,cmf10 from pm_ims_dacon group by cmf10 having count(*) > 1);
   select count(*) from pm_ims_dacon where cmf7 is null or cmf_pck is null;
   select count(*) from(select count(*) ,cmf10,effective_date from pm_ims_pricefctr_lkp group by cmf10,effective_date having count(*) > 1);
   select count(*) from pm_ims_pricefctr_lkp where cmf10 is null or effective_date is null;
   select count(*) from(select count(*) ,prd_key from pm_ims_prod_lkp group by prd_key having count(*) > 1);
   select count(*) from pm_ims_prod_lkp where prd_key is null or prd_name is null;
   select count(distinct prd_name) from pm_ims_prod_lkp;
   select count(*) from(select count(*) ,ndc from pm_fdb_rndc11 group by ndc having count(*) > 1);
   select count(*) from(select count(*) ,ndc,npt_type,npt_datec from pm_fdb_rnp1 group by ndc,npt_type,npt_datec having count(*) > 1);
   select count(*) from pm_fdb_rnp1 where ndc is null or npt_type is null or npt_datec is null;
   select count(*) from(select distinct crp,crp_name from pm_ims_corp_lkp minus select distinct corp_cd,corp_nm from c_l_lkp_corp);
   select count(*) from(select distinct delsys_code,delsys_descr from pm_ims_delsys_lkp minus select distinct delsys_cd,delsys_desc from c_l_lkp_delsys);
   select count(*) from(select distinct frm3,frm_descr from pm_ims_frm3_lkp minus select distinct form_cd,form_desc from c_l_lkp_form);
   select count(*) from(select distinct tlc_code,tlc_descr from pm_ims_tlc_lkp minus select distinct tlc_cd,tlc_desc from c_l_lkp_tlc);
   select count(*) from(select distinct usc_code,usc_descr from pm_ims_usc_lkp minus select distinct usc5_cd,usc5_desc from c_l_lkp_usc5);
   select count(*) from(select distinct mfr,mfr_abrev,mfr_name,crp from pm_ims_mfr_lkp minus select distinct mfg_cd,mfg_abrev,mfg_nm,corp_cd from c_l_lkp_mfg);
   select count(*) from(select distinct pkey_src_id,prod_desc,prod_nm from src_ims_prod_master_view where del_ind = 'N' minus select distinct pkey_src_id,prod_desc,prod_nm from c_l_prod_master where source_system = 'IMS' and del_ind = 'N');
   select count(*) from(select distinct parent_prod_id,child_prod_id from src_ims_prod_hier_view minus select distinct parent_prod_id,child_prod_id from c_l_prod_hier where source_system = 'IMS');
   select count(*) from(select distinct prod.src_prod_id from c_l_prod_master prod inner join(select distinct src_prod_id from c_l_prod_price where source_system = 'ims' minus select distinct cmf10 from pm_ims_pricefctr_lkp) diff on diff.src_prod_id = prod.src_prod_id where prod.del_ind = 'n');
   select count(*) from(select distinct pkey_src_id from c_l_prod_master where source_system = 'FDB' minus select distinct ndc from pm_fdb_rndc11);
   select count(*) from(select distinct src_prod_id from c_l_prod_price where source_system = 'FDB' minus select distinct ndc from pm_fdb_rnp1);
   select count(*) from(select distinct corp_cd,corp_nm from c_l_lkp_corp minus select distinct corp_cd,corp_nm from c_lkp_corp);
   select count(*) from(select distinct delsys_cd,delsys_desc from c_l_lkp_delsys minus select distinct delsys_cd,delsys_desc from c_lkp_delsys);
   select count(*) from(select distinct form_cd,form_desc from c_l_lkp_form minus select distinct form_cd,form_desc from c_lkp_form3);
   select count(*) from(select distinct tlc_cd,tlc_desc from c_l_lkp_tlc minus select distinct tlc_cd,tlc_desc from c_lkp_tlc);
   select count(*) from(select distinct usc5_cd,usc5_desc from c_l_lkp_usc5 minus select distinct usc5_cd,usc5_desc from c_lkp_usc5);
   select count(*) from(select distinct mfg_cd,mfg_abrev,mfg_nm,corp_cd from c_l_lkp_mfg minus select distinct mfg_cd,mfg_abrev,mfg_nm,corp_cd from c_lkp_mfg);
   select count(*) from(select distinct pkey_src_id,prod_desc,prod_nm from c_l_prod_master where source_system = 'IMS' minus select distinct src_prod_id,prod_desc,prod_nm from c_prod_master where origin_src_system = 'IMS');
   select count(*) from(select distinct PKEY_SRC_ID from c_l_prod_hier where source_system = 'IMS' minus select distinct PKEY_SRC_OBJECT from c_prod_hier_xref where ORIGIN_SRC_SYSTEM = 'IMS');
   select count(*) from(select distinct src_prod_id from c_l_prod_price where source_system = 'IMS' minus select distinct src_prod_id from c_prod_price);
   select count(*) from(select distinct pkey_src_id from c_l_prod_master where source_system = 'FDB' minus select distinct src_prod_id from c_prod_master where origin_src_system = 'FDB');
   SELECT COUNT(DISTINCT PF_MKT_ID) FROM CDW_US_PROCESSING_VW.ADS_REL_PROD_PGRPING_MAP_W A;
   SELECT COUNT(PF_MKT_ID) FROM CDW_US_PROCESSING_VW.ADS_REL_PROD_PGRPING_MAP_W A WHERE PF_MKT_ID IN(SELECT PF_MKT_ID FROM CDW_US_PROCESSING_VW.ADS_REL_PROD_PGRPING_MAP_W B WHERE PF_RGRP_ID IS NULL);
   SELECT count(PFZ_PGRPING_ID) FROM CDW_US_PROCESSING_VW.ADS_DIM_PGRPING_W WHERE CUR_IND = 1 AND PFZ_PGRPING_ID NOT IN(-1,-77777777) AND PFZ_PGRPING_ID NOT IN(SELECT PFZ_PGRPING_ID FROM CDW_US_PROCESSING_VW.ADS_REL_PROD_PGRPING_MAP_W);
   select count(distinct pf_rgrp_id) from CDW_US_PROCESSING_VW.ads_rel_prod_pgrping_map_w where PFZ_FORM_STRNG_ID = -1;
   select count(1) from(select PRODUCT_CODE from SRC_SHS_PRODUCT group by PRODUCT_CODE having count(*) > 1);
   SELECT COUNT(1) FROM CDW_US_OPERATING_VW.STG_OM_REL_CUST_PROD_EXCL;
   SELECT COUNT(1) FROM CDW_US_OPERATING_VW.STG_OM_REL_POSTAL_AREA_SALES_AREA;
   SELECT COUNT(1) FROM CDW_US_PROCESSING_VW.OM_REL_CUST_PROD_SALES_AREA;
   SELECT COUNT(1) FROM CDW_US_PROCESSING_VW.OM_REL_CUST_PROD_EXCL;
   SELECT COUNT(0) FROM(SELECT DISTINCT src_prod_id FROM c_l_prod_price WHERE source_system = 'SHS' AND origin_src_system = 'SHS' MINUS SELECT DISTINCT src_prod_id FROM c_prod_price WHERE origin_src_system = 'SHS');
   select count(*) from(select pfz_prod_id,pfz_prod_lvl from rel_prod_mkt_fctr minus select to_number(rowid_object) ,prod_level from c_prod_master where del_ind = 'N');
   select count(*) from(select COUNT(*) cnt from CDW_US_PROCESSING_VW.FCT_HCOS_CLNCL_TMP UNION select COUNT(*) cnt from CDW_US_PROCESSING_VW.FCT_HCOS_CLNCL where CUR_IND = 'Y') A;
   select count(*) from(select COUNT(*) cnt from CDW_US_PROCESSING_VW.FCT_HCOS_NTNL_CLNCL_TMP UNION select COUNT(*) cnt from CDW_US_PROCESSING_VW.FCT_HCOS_NTNL_CLNCL where CUR_IND = 'Y') a;
   select count(*) from(select COUNT(*) cnt from CDW_US_PROCESSING_VW.FCT_HCOS_ST_CLNCL_TMP UNION select COUNT(*) cnt from CDW_US_PROCESSING_VW.FCT_HCOS_ST_CLNCL where CUR_IND = 'Y') a;
   select count(*) from(select code_id from CDW_US_PROCESSING_VW.FCT_HCOS_CLNCL where del_ind = 'N' and cur_ind = 'Y' minus select code_id from CDW_US_PROCESSING_VW.DIM_HCOS_CLNCL_CD where del_ind = 'N' and cur_ind = 'Y') A;
   select count(*) from(select code_id from CDW_US_PROCESSING_VW.FCT_HCOS_ST_CLNCL where del_ind = 'N' and cur_ind = 'Y' minus select code_id from CDW_US_PROCESSING_VW.DIM_HCOS_CLNCL_CD where del_ind = 'N' and cur_ind = 'Y') A;
   select count(*) from(select code_id from CDW_US_PROCESSING_VW.FCT_HCOS_NTNL_CLNCL where del_ind = 'N' and cur_ind = 'Y' minus select code_id from CDW_US_PROCESSING_VW.DIM_HCOS_CLNCL_CD where del_ind = 'N' and cur_ind = 'Y') A;
   SELECT COUNT(*) FROM(SELECT DISTINCT pkey_src_id FROM c_l_prod_hier WHERE source_system = 'SHS' AND origin_src_system = 'SHS' MINUS SELECT DISTINCT pkey_src_object FROM c_prod_hier_xref WHERE origin_src_system = 'SHS');
   select COUNT(*) from INFORMATION_SCHEMA.TABLES where TABLE_SCHEMA = 'CDW_WORK' and TABLE_NAME like 'I1615_ADS_REL_CUST_C_SEG_W_ER%';
   select count(*) from(select sls_ety_sk,hiery_type_sk,count(*) cnt from cdw_us_processing_vw.ADS_DIM_SLS_ETY_DENOM_W group by sls_ety_sk,hiery_type_sk having count(*) > 1) A;
   SELECT count(*) FROM cdw_us_processing_vw.dim_sls_posn_w WHERE sls_posn_sk IN(SELECT DISTINCT to_sls_posn_sk FROM CDW_US_PROCESSING_VW.dim_sls_posn_hiery_expld h,rel_sls_posn_dist_st_grp d WHERE h.num_of_lvl_from_to_sls_posn < 0 AND h.sls_posn_id = d.dist_sls_posn_id MINUS SELECT a.src_sls_ety_sk FROM CDW_US_PROCESSING_VW.ads_dim_sls_ety_hiery_expld_w a);
   select count(*) from(Select clnt_cust_id from CDW_US_PROCESSING_VW.ext_adam_pres where shk_id is null Having count(ims_id) > 1 Group by clnt_cust_id) a;
   select count(*) from(select clnt_cust_id,zip_cd,count(*) ZIP_COUNT from CDW_US_PROCESSING_VW.ext_adam_pres group by clnt_cust_id,zip_cd) tmp where tmp.ZIP_COUNT > 1;
   select COUNT(*) from INFORMATION_SCHEMA.TABLES where TABLE_SCHEMA = 'CDW_WORK' and TABLE_NAME like 'I1304_STG_DIM_PROD_ER%';
   select COUNT(*) from INFORMATION_SCHEMA.TABLES where TABLE_SCHEMA = 'CDW_WORK' and TABLE_NAME like 'I1304_STG_DIM_PROD_PRIC_ER%';
   select COUNT(*) from INFORMATION_SCHEMA.TABLES where TABLE_SCHEMA = 'CDW_WORK' and TABLE_NAME like 'I1304_STG_REL_PROD_HIER_ER%';
   select COUNT(*) from INFORMATION_SCHEMA.TABLES where TABLE_SCHEMA = 'CDW_WORK' and TABLE_NAME like 'I1304_STG_DIM_PROD_XREF_ER%';
   select COUNT(*) from INFORMATION_SCHEMA.TABLES where TABLE_SCHEMA = 'CDW_WORK' and TABLE_NAME like 'I1304_STG_REL_PROD_MKT_ER%';
   select count(*) from(select pkey_src_id,origin_src_system from(select pkey_src_id,origin_src_system from c_s_ims_prod_master_prl where del_ind = 'N' union select pkey_src_id,origin_src_system from c_s_fdb_prod_master_prl where del_ind = 'N' union select pkey_src_id,origin_src_system from c_s_sec_prod_master_prl where del_ind = 'N') minus select pkey_src_object,origin_src_system from c_prod_master_xref where del_ind = 'N' and rowid_system in(select rowid_system from c_repos_system where system_name in('IMS','FDB','SEC')));
   select count(*) from(select pkey_src_object,origin_src_system from c_brand_hier_xref where del_ind = 'N' and rowid_system in(select rowid_system from c_repos_system where system_name in('IMS','FDB','SEC')) minus select * from(select pkey_src_id,origin_src_system from c_s_ims_brand_hier_prl where del_ind = 'N' union select pkey_src_id,origin_src_system from c_s_sec_brand_hier_prl where del_ind = 'N'));
   select count(*) from(select pkey_src_object,origin_src_system from c_prod_price_xref where del_ind = 'N' and rowid_system in(select rowid_system from c_repos_system where system_name in('IMS','FDB','SEC')) minus select * from(select pkey_src_id,origin_src_system from c_s_ims_prod_price_prl where del_ind = 'N' union select pkey_src_id,origin_src_system from c_s_fdb_prod_price_prl where del_ind = 'N' union select pkey_src_id,origin_src_system from c_s_sec_prod_price_prl where del_ind = 'N'));
   select count(*) from(select pkey_src_object,origin_src_system from c_mkt_std_hier_xref where del_ind = 'N' and rowid_system in(select rowid_system from c_repos_system where system_name in('IMS','FDB','SEC')) minus select pkey_src_id,origin_src_system from c_s_pfz_mkt_std_hier_prl where del_ind = 'N');
   select count(*) from(select * from(select pkey_src_object,origin_src_system from c_s_ims_prod_master where del_ind = 'N' union select pkey_src_object,origin_src_system from c_s_fdb_prod_master where del_ind = 'N' union select pkey_src_object,origin_src_system from c_s_sec_prod_master where del_ind = 'N') minus select pkey_src_object,origin_src_system from c_prod_master_xref where del_ind = 'N' and rowid_system in(select rowid_system from c_repos_system where system_name in('IMS','FDB','SEC')));
   select count(*) from CDW_US_PROCESSING_VW.RPT_PM_ERRORS_V where test_id = 108;
   select count(*) from CDW_US_PROCESSING_VW.RPT_PM_ERRORS_V where test_id = 122;
   select count(*) from(select PFZ_RPT_GRP_ID,count(distinct pfz_prod_id) cnt from c_mkt_std_hier where 1 = 1 and HIERARCHY_ID = 'SALES' and PROD_LEVEL = 'UNKNOWN' and del_ind = 'N' and pfz_prod_id in(select distinct prd.rowid_object from c_prod_master prd,c_prod_master_xref xref where prd.rowid_object = xref.rowid_object and xref.ORIGIN_SRC_SYSTEM = 'HCX' and prd.del_ind = 'N' and xref.del_ind = 'N') group by PFZ_RPT_GRP_ID having count(distinct pfz_prod_id) > 1);
   select count(*) from CDW_US_PROCESSING_VW.RPT_PM_ERRORS_V where test_id = 106;
   select count(*) from CDW_US_PROCESSING_VW.RPT_PM_ERRORS_V where test_id = 112;
   select count(*) from CDW_US_PROCESSING_VW.RPT_PM_ERRORS_V where test_id = 118;
   select count(*) from CDW_US_PROCESSING_VW.RPT_PM_ERRORS_V where test_id = 119;
   select count(*) from CDW_US_PROCESSING_VW.RPT_PM_ERRORS_V where test_id = 120;
   select count(*) from CDW_US_PROCESSING_VW.RPT_PM_ERRORS_V where test_id = 121;
   select COUNT(*) from INFORMATION_SCHEMA.TABLES where TABLE_SCHEMA = 'CDW_WORK' and TABLE_NAME like 'l1304_S_MKT_FCTR%';
   select count(*) from(select PFZ_RPT_GRP_ID,count(distinct pfz_prod_id) cnt from c_mkt_std_hier where 1 = 1 and HIERARCHY_ID = 'SALES' and PROD_LEVEL = 'UNKNOWN' and del_ind = 'N' and pfz_prod_id in(select distinct prd.rowid_object from c_prod_master prd,c_prod_master_xref xref where prd.rowid_object = xref.rowid_object and xref.ORIGIN_SRC_SYSTEM = 'HCX' and prd.del_ind = 'N' and xref.del_ind = 'N') group by PFZ_RPT_GRP_ID having count(distinct pfz_prod_id) > 1);
   select count(*) from(select pkey_src_id,origin_src_system from(select pkey_src_id,origin_src_system from c_s_ims_prod_master_prl where del_ind = 'N' union select pkey_src_id,origin_src_system from c_s_fdb_prod_master_prl where del_ind = 'N' union select pkey_src_id,origin_src_system from c_s_sec_prod_master_prl where del_ind = 'N') minus select pkey_src_object,origin_src_system from c_prod_master_xref where del_ind = 'N' and rowid_system in(select rowid_system from c_repos_system where system_name in('IMS','FDB','SEC')));
   select count(*) from(select pkey_src_object,origin_src_system from c_brand_hier_xref where del_ind = 'N' and rowid_system in(select rowid_system from c_repos_system where system_name in('IMS','FDB','SEC')) minus select * from(select pkey_src_id,origin_src_system from c_s_ims_brand_hier_prl where del_ind = 'N' union select pkey_src_id,origin_src_system from c_s_sec_brand_hier_prl where del_ind = 'N'));
   select count(*) from(select pkey_src_object,origin_src_system from c_prod_price_xref where del_ind = 'N' and rowid_system in(select rowid_system from c_repos_system where system_name in('IMS','FDB','SEC')) minus select * from(select pkey_src_id,origin_src_system from c_s_ims_prod_price_prl where del_ind = 'N' union select pkey_src_id,origin_src_system from c_s_fdb_prod_price_prl where del_ind = 'N'));
   select count(*) from(select pkey_src_object,origin_src_system from c_mkt_std_hier_xref where del_ind = 'N' and rowid_system in(select rowid_system from c_repos_system where system_name in('IMS','FDB','SEC')) minus select pkey_src_id,origin_src_system from c_s_pfz_mkt_std_hier_prl where del_ind = 'N');
   select count(*) from(select * from(select pkey_src_object,origin_src_system from c_s_ims_prod_master where del_ind = 'N' union select pkey_src_object,origin_src_system from c_s_fdb_prod_master where del_ind = 'N' union select pkey_src_object,origin_src_system from c_s_sec_prod_master where del_ind = 'N') minus select pkey_src_object,origin_src_system from c_prod_master_xref where del_ind = 'N' and rowid_system in(select rowid_system from c_repos_system where system_name in('IMS','FDB','SEC')));
   select count(*) from(select * from(select pkey_src_object,origin_src_system from c_s_ims_brand_hier where del_ind = 'N' union select pkey_src_object,origin_src_system from c_s_sec_brand_hier where del_ind = 'N') minus select pkey_src_object,origin_src_system from c_brand_hier_xref where del_ind = 'N' and rowid_system in(select rowid_system from c_repos_system where system_name in('IMS','FDB','SEC')));
   select count(*) from(select pkey_src_object,origin_src_system from(select pkey_src_object,origin_src_system from c_s_ims_prod_price where del_ind = 'N' union select pkey_src_object,origin_src_system from c_s_fdb_prod_price where del_ind = 'N') minus select pkey_src_object,origin_src_system from c_prod_price_xref where del_ind = 'N' and rowid_system in(select rowid_system from c_repos_system where system_name in('IMS','FDB','SEC')));
   select count(*) from(select pkey_src_object,origin_src_system from c_s_pfz_mkt_std_hier where del_ind = 'N' minus select pkey_src_object,origin_src_system from c_mkt_std_hier_xref where del_ind = 'N' and rowid_system in(select rowid_system from c_repos_system where system_name in('IMS','FDB','SEC')));
   select count(*) from RPT_PM_ERRORS_V where test_id = 108;
   select count(*) from RPT_PM_ERRORS_V where test_id = 122;
   select count(*) from RPT_PM_ERRORS_V where test_id = 106;
   select count(*) from RPT_PM_ERRORS_V where test_id = 112;
   select count(*) from RPT_PM_ERRORS_V where test_id = 118;
   select count(*) from RPT_PM_ERRORS_V where test_id = 119;
   select count(*) from RPT_PM_ERRORS_V where test_id = 120;
   select count(*) from RPT_PM_ERRORS_V where test_id = 121;
   SELECT COUNT(*) FROM C_L_PROD_PRICE WHERE PRICE_EFFECTIVE_DT > PRICE_END_DT AND ORIGIN_SRC_SYSTEM = 'IMS' AND DEL_IND = 'N';
   SELECT COUNT(1) FROM CDW_US_OPERATING_VW.STG_OM_DIM_EMPLOYEE_ADDRESS;
   SELECT COUNT(1) FROM CDW_US_OPERATING_VW.STG_OM_REL_EMP_SALES_AREA;
   SELECT COUNT(1) FROM CDW_US_OPERATING_VW.STG_OM_DIM_EMPLOYEE_STATUS;
   SELECT COUNT(1) FROM CDW_US_OPERATING_VW.STG_OM_DIM_POSTAL_AREA;
   SELECT COUNT(1) FROM CDW_US_OPERATING_VW.STG_OM_DIM_PRODUCT;
   SELECT COUNT(1) FROM CDW_US_OPERATING_VW.STG_OM_REL_PROD_SALES_AREA;
   SELECT COUNT(1) FROM CDW_US_OPERATING_VW.STG_OM_REL_PRODUCT_SALES_AREA_EXCEP;
   SELECT COUNT(1) FROM CDW_US_OPERATING_VW.STG_OM_DIM_SALES_AREA;
   SELECT COUNT(1) FROM CDW_US_OPERATING_VW.STG_OM_DIM_SALES_AREA_PRPTY_TYPE;
   SELECT COUNT(1) FROM CDW_US_OPERATING_VW.STG_OM_DIM_SALES_AREA_RELATION;
   SELECT COUNT(1) FROM CDW_US_OPERATING_VW.STG_OM_REL_SALES_AREA_SALES_FORCE;
   SELECT COUNT(1) FROM CDW_US_OPERATING_VW.STG_OM_DIM_SALES_FORCE;
   SELECT COUNT(1) FROM CDW_US_PROCESSING_VW.OM_DIM_EMPLOYEE;
   SELECT COUNT(1) FROM CDW_US_PROCESSING_VW.OM_DIM_EMPLOYEE_ADDRESS;
   SELECT COUNT(1) FROM CDW_US_PROCESSING_VW.OM_REL_EMP_SALES_AREA;
   SELECT COUNT(1) FROM CDW_US_PROCESSING_VW.OM_DIM_EMPLOYEE_STATUS;
   SELECT COUNT(1) FROM CDW_US_PROCESSING_VW.OM_DIM_POSTAL_AREA;
   SELECT COUNT(1) FROM CDW_US_PROCESSING_VW.OM_DIM_PRODUCT;
   SELECT COUNT(1) FROM CDW_US_PROCESSING_VW.OM_REL_PROD_SALES_AREA;
   SELECT COUNT(1) FROM CDW_US_PROCESSING_VW.OM_REL_PROD_SALES_AREA_EXCE;
   SELECT COUNT(1) FROM CDW_US_PROCESSING_VW.OM_DIM_SALES_AREA;
   SELECT COUNT(1) FROM CDW_US_PROCESSING_VW.OM_DIM_SALES_AREA_PRPTY_TYPE;
   SELECT COUNT(1) FROM CDW_US_PROCESSING_VW.OM_DIM_SALES_AREA_RELATION;
   SELECT COUNT(1) FROM CDW_US_PROCESSING_VW.OM_REL_SALES_AREA_SALES_FORCE;
   SELECT COUNT(1) FROM CDW_US_PROCESSING_VW.OM_DIM_SALES_FORCE;
   SELECT COUNT(*) FROM CDW_US_PROCESSING_VW.ADS_DIM_PGRPING_W WHERE PFZ_FORM_STRG_ID = -1 and cur_ind = 1;
   SELECT COUNT(*) FROM CDW_US_PROCESSING_VW.ADS_DIM_PGRPING_W WHERE PFZ_FORM_STRG_ID <> -1 and cur_ind = 1;
   SELECT COUNT(*) FROM CDW_US_PROCESSING_VW.ADS_DIM_MKT_GRP_W WHERE CUR_IND = 1 AND DEL_IND = 0;
   SELECT COUNT(*) FROM CDW_US_PROCESSING_VW.ADS_REL_MKT_MKT_GRP_MAP_W;
   select count(*) from CDW_US_PROCESSING_VW.ads_rel_prod_pgrping_map_w where PFZ_FORM_STRNG_ID = -1;
   select count(*) from CDW_US_PROCESSING_VW.ads_rel_prod_pgrping_map_w where PFZ_FORM_STRNG_ID <> -1;
   select count(*) from(select distinct a.pfz_cust_id,TRIM(COALESCE(b.fname,'')) as hcp_fname,TRIM(COALESCE(b.midl_nm,'')) as hcp_mname,TRIM(COALESCE(b.lname,'')) as hcp_lname,b.titl_cd as hcp_cdtl,b.ims_cust_id,d.st_cd,d.st_lic_num,d.sln_exprn_dt,d.sln_authn_stat_cd from(select distinct x.pfz_cust_id from CDW_US_PROCESSING_VW.dim_cust_hcp x inner join CDW_US_PROCESSING_VW.dim_cust_xref y on x.pfz_cust_id = y.pfz_cust_id and x.pres_prof_type_id = '00' and y.src_sys in('VVA','IMS') and x.cur_ind = 'Y' and x.del_ind = 'N' and y.cur_ind = 'Y' and y.del_ind = 'N') a inner join CDW_US_PROCESSING_VW.dim_cust_hcp b on a.pfz_cust_id = b.pfz_cust_Id inner join CDW_US_PROCESSING_VW.dim_cust_sln d on(b.pfz_cust_Id = d.pfz_cust_id and d.cur_ind = 'Y' and d.del_ind = 'N')) t;
   select sum(A) from(select count(distinct PFZ_PLAN_ID) + count(distinct PFZ_MCO_ID) + count(distinct PFZ_MCO_PRNT_ID) + count(distinct PFZ_PYR_ENTP_ID) A from CDW_US_PROCESSING_VW.dim_cust_plan_hiery union select count(distinct PFZ_PBM_ID) + count(distinct PFZ_PBM_PRNT_ID) + count(distinct PFZ_PBM_VNDR_ID) A from CDW_US_PROCESSING_VW.dim_cust_plan_hiery where PFZ_PBM_ID <> -1 union select count(*) *(-1) A from cdw_us_processing_vw.ads_dim_pyr_w) B;
   select count(distinct pfz_cust_id) from(select distinct a.pfz_cust_id,TRIM(COALESCE(b.fname,'')) as hcp_fname,TRIM(COALESCE(b.midl_nm,'')) as hcp_mname,TRIM(COALESCE(b.lname,'')) as hcp_lname,b.titl_cd as hcp_cdtl,b.ims_cust_id,d.st_cd,d.st_lic_num,d.sln_exprn_dt,d.sln_authn_stat_cd from(select distinct x.pfz_cust_id from CDW_US_PROCESSING_VW.dim_cust_hcp x inner join CDW_US_PROCESSING_VW.dim_cust_xref y on x.pfz_cust_id = y.pfz_cust_id and x.pres_prof_type_id = '00' and y.src_sys in('VVA','IMS') and x.cur_ind = 'Y' and x.del_ind = 'N' and y.cur_ind = 'Y' and y.del_ind = 'N') a inner join CDW_US_PROCESSING_VW.dim_cust_hcp b on a.pfz_cust_id = b.pfz_cust_Id inner join CDW_US_PROCESSING_VW.dim_cust_sln d on(b.pfz_cust_Id = d.pfz_cust_id and d.cur_ind = 'Y' and d.del_ind = 'N')) t;
   select sum(A) from(select count(1) A from(SELECT PFZ_PLAN_ID,PFZ_PLAN_ID FROM CDW_US_PROCESSING_VW.dim_cust_plan_hiery UNION SELECT PFZ_PLAN_ID,pfz_mco_id FROM CDW_US_PROCESSING_VW.dim_cust_plan_hiery UNION SELECT PFZ_PLAN_ID,PFZ_MCO_PRNT_ID FROM CDW_US_PROCESSING_VW.dim_cust_plan_hiery UNION SELECT PFZ_PLAN_ID,PFZ_PYR_ENTP_ID FROM CDW_US_PROCESSING_VW.dim_cust_plan_hiery UNION SELECT PFZ_PLAN_ID,PFZ_PBM_ID FROM CDW_US_PROCESSING_VW.dim_cust_plan_hiery WHERE PFZ_PBM_ID <> -1 UNION SELECT PFZ_PLAN_ID,PFZ_PBM_PRNT_ID FROM CDW_US_PROCESSING_VW.dim_cust_plan_hiery WHERE PFZ_PBM_ID <> -1 UNION SELECT PFZ_PLAN_ID,PFZ_PBM_VNDR_ID FROM CDW_US_PROCESSING_VW.dim_cust_plan_hiery WHERE PFZ_PBM_ID <> -1) AA union Select count(1) *(-1) A from CDW_US_PROCESSING_VW.ADS_REL_PLAN_PYR_W) B;
   SELECT COUNT(1) FROM TEMP_IMS_VALDN_STG WHERE (FRST_NM) is null AND(LAST_NM) is null AND(ADDR_1) is null AND(CITY) is null AND(ST_OR_PRVC_CD) is null AND(ZIP_OR_POST_CD) is null;
   SELECT COUNT(1) FROM TEMP_IMS_VALDN_STG;
   SELECT COUNT(1) FROM IMS_VALDN_STG;
   SELECT count(DISTINCT a.sls_ety_sk) FROM CDW_US_PROCESSING_VW.ads_dim_sls_ety_hiery_expld_w a WHERE a.num_of_lvl_from_to_sls_ety <> 0 AND a.sls_ety_role_cd IN('STATE','SUB STATE') AND NOT EXISTS(SELECT b.sls_ety_sk FROM CDW_US_PROCESSING_VW.ads_dim_sls_ety_hiery_expld_w b WHERE b.num_of_lvl_from_to_sls_ety > 0 AND a.sls_ety_sk = b.to_sls_ety_sk);
   select count(*) from(select sls_ety_sk,count(*) cnt1 from CDW_US_PROCESSING_VW.ADS_DIM_SLS_ETY_DENOM_w group by sls_ety_sk having count(*) > 1) a;
   SELECT count(DISTINCT a.sls_ety_sk) FROM CDW_US_PROCESSING_VW.ads_dim_sls_ety_hiery_expld_w a WHERE a.num_of_lvl_from_to_sls_ety <> 0 AND a.sls_ety_role_cd IN('DM') AND NOT EXISTS(SELECT b.sls_ety_sk FROM CDW_US_PROCESSING_VW.ads_dim_sls_ety_hiery_expld_w b WHERE b.num_of_lvl_from_to_sls_ety > 0 AND a.sls_ety_sk = b.to_sls_ety_sk);
   SELECT COUNT(0) FROM CDW_US_PROCESSING_VW.ads_dim_sls_ety_hiery_expld_w WHERE lvl_in_hiery = 2 AND num_of_lvl_from_to_sls_ety = 0 AND bu_sk = -10;
   SELECT COUNT(0) FROM CDW_US_PROCESSING_VW.ads_dim_sls_ety_hiery_expld_w WHERE lvl_in_hiery = 2 AND num_of_lvl_from_to_sls_ety = 0 AND bu_sk = 21;
   SELECT COUNT(0) FROM CDW_US_PROCESSING_VW.ads_dim_sls_ety_hiery_expld_w WHERE lvl_in_hiery = 2 AND num_of_lvl_from_to_sls_ety = 0 AND bu_sk = 41;
   SELECT COUNT(0) FROM CDW_US_PROCESSING_VW.ads_dim_sls_ety_hiery_expld_w WHERE lvl_in_hiery = 2 AND num_of_lvl_from_to_sls_ety = 0 AND bu_sk = 42;
   SELECT COUNT(SLS_ETY_SK) FROM CDW_US_PROCESSING_VW.ADS_DIM_SLS_ETY_HIERY_EXPLD_W WHERE NUM_OF_LVL_FROM_TO_SLS_ETY = 1 AND TO_SLS_ETY_ROLE_CD = 'RBU';
   SELECT COUNT(0) FROM CDW_US_PROCESSING_VW.ads_dim_sls_ety_hiery_expld_w WHERE lvl_in_hiery = 2 AND num_of_lvl_from_to_sls_ety = 0 AND bu_sk = 9;
   SELECT COUNT(*) FROM(select SLS_POSN_SK from CDW_US_PROCESSING_VW.DIM_SLS_POSN_HIERY_DENOM WHERE SORG_SK IN(7,10,16,17,20) AND CUR_IND = 'Y' AND DEL_IND = 'N' AND SLS_ROLE_CD IN ('DM','GDM','FDM','CAD','CDM','IDM','SM') MINUS SELECT DIST_SLS_POSN_SK FROM CDW_US_PROCESSING_VW.REL_SLS_POSN_DIST_ST_GRP) A;
   select COUNT(*) from INFORMATION_SCHEMA.TABLES where TABLE_SCHEMA = 'CDW_WORK' and TABLE_NAME like 'I1615_ADS_R_PRESC_ETY_MKT_ER%';
   SELECT COUNT(*) FROM CDW_US_PROCESSING_VW.ADS_DIM_SLS_ETY_LIST_W WHERE CUR_IND = 1 and SLS_ETY_ROLE_CD = 'POLITICAL_STATE' GROUP BY SLS_ETY_ROLE_CD;
   SELECT COUNT(*) FROM CDW_US_PROCESSING_VW.ADS_DIM_SLS_ETY_LIST_W WHERE CUR_IND = 1 and SLS_ETY_ROLE_CD = 'STATE' GROUP BY SLS_ETY_ROLE_CD;
   SELECT COUNT(*) FROM CDW_US_PROCESSING_VW.ADS_DIM_SLS_ETY_LIST_W WHERE CUR_IND = 1 and SLS_ETY_ROLE_CD = 'SUB STATE' GROUP BY SLS_ETY_ROLE_CD;
   SELECT COUNT(*) FROM CDW_US_PROCESSING_VW.ADS_DIM_SLS_ETY_LIST_W WHERE CUR_IND = 1 and SLS_ETY_ROLE_CD = 'RBU' GROUP BY SLS_ETY_ROLE_CD;
   select count(*) from(select sls_ety_nm,sls_ety_role_cd from CDW_US_PROCESSING_VW.ads_dim_sls_ety_list_w where sls_ety_sk in(SELECT sls_ety_sk from CDW_US_PROCESSING_VW.ads_dim_sls_ety_list_w where cur_ind = 1 minus select from_sls_ety_sk from CDW_US_PROCESSING_VW.ads_rel_sls_ety_w)) a;
   select count(0) from CDW_US_PROCESSING_VW.ads_rel_sls_ety_w where SRC_OF_HIERY_DESC like 'EPBU%';
   select count(*) from CDW_US_PROCESSING_VW.ads_rel_sls_ety_w where to_sls_ety_sk = from_sls_ety_sk;
   SELECT count(*) from(select from_sls_ety_sk,hiery_type_sk,count(to_sls_ety_sk) cnt from CDW_US_PROCESSING_VW.ads_rel_sls_ety_w group by from_sls_ety_sk,hiery_type_sk having count(to_sls_ety_sk) > 1) A;
   SELECT COUNT(*) FROM(SELECT DISTINCT lvl_in_hiery FROM CDW_US_PROCESSING_VW.ads_dim_sls_ety_hiery_expld_w WHERE num_of_lvl_from_to_sls_ety = 0) a;
   SELECT COUNT(0) FROM CDW_US_PROCESSING_VW.ads_dim_sls_ety_hiery_expld_w WHERE lvl_in_hiery = 1 AND num_of_lvl_from_to_sls_ety = 0;
   SELECT COUNT(0) FROM CDW_US_PROCESSING_VW.ads_dim_sls_ety_hiery_expld_w WHERE lvl_in_hiery = 2 AND num_of_lvl_from_to_sls_ety = 0;
   select count(0) from CDW_US_PROCESSING_VW.ADS_DIM_SLS_ETY_HIERY_EXPLD_W where sls_ety_role_cd like 'EPBU%';
   select COUNT(*) from INFORMATION_SCHEMA.TABLES where TABLE_SCHEMA = 'CDW_WORK' and TABLE_NAME like 'I1615_ADS_STG_R2_VAL_UNM1_ER%';
   select COUNT(*) from INFORMATION_SCHEMA.TABLES where TABLE_SCHEMA = 'CDW_WORK' and TABLE_NAME like 'I1615_ADS_R_PRESC_ETY_MKT2_ER%';
   select COUNT(*) from INFORMATION_SCHEMA.TABLES where TABLE_SCHEMA = 'CDW_WORK' and TABLE_NAME like 'I1615_ADS_SLS_ETY_ZIP_MKT_ER%';
   SELECT COUNT(DISTINCT PFZ_MKT_ID) FROM CDW_US_PROCESSING_VW.ADS_REL_PRESC_ETY_MKT_W WHERE PROF_ID IN(-10,-20);
   select count(*) from(SELECT a.pfz_cust_id FROM CDW_US_PROCESSING_VW.ADS_STG_PYR_SLS_PRESC a MINUS SELECT b.pfz_pres_id FROM CDW_US_PROCESSING_VW.ADS_REL_PRESC_ETY_MKT_W b) a;
   select count(*) from(select PROF_ID,SEG_ID from CDW_US_PROCESSING_VW.ADS_REL_PRESC_ETY_MKT_W minus select R2_PROD_RANK_GRP_ID,R2_TERR_RANK_GRP_ID from CDW_US_PROCESSING_VW.ads_rel_r2_rank_to_seg_map_w where RPT_APPL_SK = 1) A;
   select COUNT(*) from INFORMATION_SCHEMA.TABLES where TABLE_SCHEMA = 'CDW_WORK' and TABLE_NAME like 'I1615_WYTH_ADS_REL_S_SEG_ER%';
   select count(*) from CDW_US_PROCESSING_VW.ads_dim_sls_ety_hiery_expld_w where sls_ety_sk in(select sls_ety_sk from CDW_US_PROCESSING_VW.ads_dim_sls_ety_hiery_expld_w minus select sls_ety_sk from CDW_US_PROCESSING_VW.ADS_DIM_SLS_ETY_DENOM_w) and num_of_lvl_from_to_sls_ety = 0;
   SELECT count(1) FROM C_PARTY_EXTL_ID A WHERE A.MRM_SOFT_DLT_IND in('Y','P') AND EXISTS(SELECT 1 FROM C_PARTY_EXTL_ID_XREF B WHERE B.MRM_SOFT_DLT_IND = 'N' AND B.ROWID_OBJECT = A.ROWID_OBJECT);
   SELECT COUNT(1) FROM CDW_US_OPERATING_VW.STG_OM_DIM_EMPLOYEE;
   SELECT COUNT(0) FROM(SELECT DISTINCT parent_prod_id,child_prod_id,COUNT(0) FROM c_l_prod_hier WHERE source_system = 'SHS' AND origin_src_system = 'SHS' AND DEL_IND = 'N' GROUP BY parent_prod_id,child_prod_id HAVING COUNT(0) > 1);
   SELECT COUNT(*) FROM PMX_ORS.C_PROD_MASTER WHERE ORIGIN_SRC_SYSTEM = 'SHS' AND DEL_IND = 'N';
   SELECT COUNT(*) FROM CDW_US_DIMS_DB.SRC_SHS_PROD_IMS_MATCH;
   select abs(R1.SQLRESULT - R2.SQLRESULT) SQLRESULT from(SELECT * FROM CIF.QCT_INF_RESULTS QIR1 WHERE(QIR1.CYCLEID,QIR1.TESTID) in(SELECT MAX(QIR2.CYCLEID) ,QIR2.TESTID FROM CIF.QCT_INF_RESULTS QIR2 WHERE QIR2.TESTID = 1753011 GROUP BY QIR2.TESTID)) R1,CIF.QCT_INF_RESULTS R2 WHERE R1.CYCLEID = R2.CYCLEID and R1.INTERFACEID = R2.INTERFACEID and R1.POSITION = R2.POSITION and R1.SESSIONNAME = R2.SESSIONNAME and R2.TESTID = 1753012;
   select abs(R1.SQLRESULT - R2.SQLRESULT) SQLRESULT from(SELECT * FROM CIF.QCT_INF_RESULTS QIR1 WHERE(QIR1.CYCLEID,QIR1.TESTID) in(SELECT MAX(QIR2.CYCLEID) ,QIR2.TESTID FROM CIF.QCT_INF_RESULTS QIR2 WHERE QIR2.TESTID = 1753011 GROUP BY QIR2.TESTID)) R1,CIF.QCT_INF_RESULTS R2 WHERE R1.CYCLEID = R2.CYCLEID and R1.INTERFACEID = R2.INTERFACEID and R1.POSITION = R2.POSITION and R1.SESSIONNAME = R2.SESSIONNAME and R2.TESTID = 1753012;
   select abs(R1.SQLRESULT - R2.SQLRESULT) SQLRESULT from(SELECT * FROM CIF.QCT_INF_RESULTS QIR1 WHERE(QIR1.CYCLEID,QIR1.TESTID) in(SELECT MAX(QIR2.CYCLEID) ,QIR2.TESTID FROM CIF.QCT_INF_RESULTS QIR2 WHERE QIR2.TESTID = 1753011 GROUP BY QIR2.TESTID)) R1,CIF.QCT_INF_RESULTS R2 WHERE R1.CYCLEID = R2.CYCLEID and R1.INTERFACEID = R2.INTERFACEID and R1.POSITION = R2.POSITION and R1.SESSIONNAME = R2.SESSIONNAME and R2.TESTID = 1753012;
   SELECT COUNT(*) FROM(SELECT SHS_NDC11_CD FROM CDW_US_DIMS_DB.SRC_SHS_PROD_IMS_MATCH GROUP BY SHS_NDC11_CD HAVING COUNT(*) > 1) A;
   SELECT COUNT(*) FROM(SELECT OM_CUSTOMER_PRD_SALES_AREA_SK FROM(SELECT OM_CUSTOMER_PRD_SALES_AREA_SK FROM CDW_US_PROCESSING_VW.OM_REL_CUST_PROD_SALES_AREA MINUS SELECT OM_CUSTOMER_PRD_SALES_AREA_SK FROM CDW_US_PROCESSING_VW.OMODS_CPA_DEL) DIFF_SK) DIFF_CNT;
   SELECT COUNT(1) FROM CDW_US_PROCESSING_VW.OM_REL_POSTAL_AREA_SALES_AREA;
   select count(*) from(select DISTINCT(PRODUCT_BRAND) from pmx_ors.PM_SND_GEN_STG WHERE VALID_FG = 'Y' AND ORIGIN_SRC_SYSTEM = 'MLG' minus select prod_nm from pmx_ors.c_prod_master where prod_level = 'RPTGRP' AND DEL_IND = 'N' AND PROD_GROUP_TYPE = 'P');
   