USE ROLE COMM_DOMAIN_ADMIN;

GRANT ROLE COMM__ETL_DEV_WH_USAGE_ROLE to ROLE COMM_DEV_CDW_SRVC_ACCT_ROLE;
GRANT ROLE COMM__ETL_DEV_WH_USAGE_ROLE to ROLE COMM_DEV_PUB_SRVC_ACCT_ROLE;-- update this
GRANT ROLE COMM__PUB_DEV_WH_USAGE_ROLE to ROLE COMM_DEV_RPT_SRVC_ACCT_ROLE;

GRANT ROLE COMM__USER_DEV_WH_USAGE_ROLE to ROLE COMM_DEV_CDW_DEVELOPER_ROLE; -- update this

GRANT ROLE COMM__USER_DEV_WH_USAGE_ROLE to ROLE COMM_DEV_CDW_STNDRD_ROLE;

GRANT ROLE COMM__ETL_DEV_WH_USAGE_ROLE to ROLE COMM_DEV_CDW_L2_L3_ROLE;
GRANT ROLE COMM__PUB_DEV_WH_USAGE_ROLE to ROLE COMM_DEV_CDW_L2_L3_ROLE;
GRANT ROLE COMM__USER_DEV_WH_USAGE_ROLE to ROLE COMM_DEV_CDW_L2_L3_ROLE;

GRANT ROLE COMM__ETL_DEV_WH_USAGE_ROLE to ROLE COMM_DEV_CDW_OPS_ROLE;
GRANT ROLE COMM__PUB_DEV_WH_USAGE_ROLE to ROLE COMM_DEV_CDW_OPS_ROLE;
GRANT ROLE COMM__USER_DEV_WH_USAGE_ROLE to ROLE COMM_DEV_CDW_OPS_ROLE;


