USE ROLE COMM_DOMAIN_ADMIN;

CREATE ROLE COMM__ETL_DEV_WH_USAGE_ROLE; 
CREATE ROLE COMM__PUB_DEV_WH_USAGE_ROLE; 
CREATE ROLE COMM__USER_DEV_WH_USAGE_ROLE;

GRANT OPERATE,USAGE ON WAREHOUSE COMM_US_ETL_XS_WH TO role COMM__ETL_DEV_WH_USAGE_ROLE;
GRANT OPERATE,USAGE ON WAREHOUSE COMM_US_ETL_S_WH  TO role COMM__ETL_DEV_WH_USAGE_ROLE;
GRANT OPERATE,USAGE ON WAREHOUSE COMM_US_ETL_M_WH  TO role COMM__ETL_DEV_WH_USAGE_ROLE;
GRANT OPERATE,USAGE ON WAREHOUSE COMM_US_ETL_L_WH  TO role COMM__ETL_DEV_WH_USAGE_ROLE;
GRANT OPERATE,USAGE ON WAREHOUSE COMM_US_ETL_XL_WH TO role COMM__ETL_DEV_WH_USAGE_ROLE;

GRANT USAGE ON WAREHOUSE COMM_US_RPT_LIVE_WH TO role COMM__PUB_DEV_WH_USAGE_ROLE;
GRANT USAGE ON WAREHOUSE COMM_US_RPT_EXTRACT_WH TO role COMM__PUB_DEV_WH_USAGE_ROLE;


GRANT USAGE ON WAREHOUSE COMM_US_USER_XS_WH  TO role COMM__USER_DEV_WH_USAGE_ROLE;
